# Generated by Django 4.2.11 on 2024-04-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图表名称')),
                ('expression', models.CharField(max_length=100, verbose_name='表达式')),
                ('mapping', models.TextField(blank=True, null=True, verbose_name='映射')),
                ('default', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='默认值')),
                ('unit', models.CharField(max_length=25, verbose_name='单位')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('sort_weight', models.IntegerField(help_text='值越小排序越靠前', verbose_name='排序值')),
                ('remark', models.TextField(default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '流量图表',
                'verbose_name_plural': '流量图表',
                'db_table': 'netflow_chart',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategoryModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('sort_weight', models.IntegerField(help_text='值越小排序越靠前', verbose_name='排序值')),
                ('remark', models.TextField(default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单栏一级分类',
                'verbose_name_plural': '菜单栏一级分类',
                'db_table': 'netflow_menu_category',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_weight', models.IntegerField(help_text='值越小排序越靠前', verbose_name='排序值')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', related_query_name='sub_category', to='app_netflow.menucategorymodel', verbose_name='类别')),
                ('chart', models.ManyToManyField(blank=True, related_name='menu_list', related_query_name='menu', to='app_netflow.chartmodel', verbose_name='图表合集')),
            ],
            options={
                'verbose_name': '菜单栏',
                'verbose_name_plural': '菜单栏',
                'db_table': 'netflow_menu',
                'ordering': ['sort_weight'],
            },
        ),
    ]
