# Generated by Django 4.2.11 on 2024-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_netflow', '0002_alter_chartmodel_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
