# Generated by Django 4.2.9 on 2024-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_netflow', '0005_alter_chartmodel_options_alter_menumodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='charts',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='users',
        ),
        migrations.AddField(
            model_name='chartmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='MenuModel',
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
    ]
