# Generated by Django 4.2.4 on 2023-08-29 08:00

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255, verbose_name='邮件服务')),
                ('subject', models.CharField(max_length=255, verbose_name='标题')),
                ('sender', models.EmailField(default='', max_length=254, verbose_name='发送者')),
                ('receiver', models.CharField(max_length=254, verbose_name='接收者')),
                ('message', models.TextField(verbose_name='邮件内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tag', models.CharField(choices=[('year', '年度报表'), ('month', '月度报表'), ('ticket', '工单通知'), ('coupon', '资源券通知'), ('res-exp', '资源过期通知'), ('api', 'API请求'), ('other', '其他')], default='other', max_length=16, verbose_name='标签')),
                ('is_html', models.BooleanField(default=False, verbose_name='html格式信息')),
                ('status', models.CharField(choices=[('wait', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='success', max_length=16, verbose_name='发送状态')),
                ('status_desc', models.CharField(default='', max_length=255, verbose_name='状态描述')),
                ('success_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='成功发送时间')),
                ('remote_ip', models.CharField(default='', max_length=64, verbose_name='客户端ip')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'ordering': ['-send_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('company', models.CharField(default='', max_length=255, verbose_name='公司/单位')),
                ('third_app', models.SmallIntegerField(choices=[(0, '本地用户'), (1, '科技云通行证'), (2, '身份认证联盟AAI')], default=0, verbose_name='第三方应用登录')),
                ('last_active', models.DateTimeField(auto_now=True, db_index=True, verbose_name='最后活跃日期')),
                ('role', models.JSONField(default=users.models.default_role, help_text="角色选项(可多选)，['ordinary', 'vms-admin', 'storage-admin', 'federal-admin']", verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
