# Generated by Django 2.2.15 on 2020-09-17 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='最后活跃日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='third_app',
            field=models.SmallIntegerField(choices=[(0, '本地用户'), (1, '科技云通行证')], default=0, verbose_name='第三方应用登录'),
        ),
    ]
