# Generated by Django 3.2.13 on 2023-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230526_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='remote_ip',
            field=models.CharField(default='', max_length=64, verbose_name='客户端ip'),
        ),
    ]
