# Generated by Django 3.1.7 on 2021-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210204_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-send_time'], 'verbose_name': '邮件', 'verbose_name_plural': '邮件'},
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
