# Generated by Django 3.1.7 on 2021-04-09 01:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210331_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.JSONField(default=users.models.default_role, help_text="角色选项(可多选)，['ordinary', 'vms-admin', 'storage-admin', 'federal-admin']", verbose_name='角色'),
        ),
    ]
