# Generated by Django 3.2.13 on 2023-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20220901_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsservice',
            name='endpoint_url',
            field=models.CharField(help_text='http(s)://{hostname}:{port}/', max_length=255, verbose_name='服务地址url'),
        ),
    ]
