# Generated by Django 3.2.13 on 2023-03-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_objectsservice_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='situation',
            field=models.CharField(choices=[('normal', '正常'), ('arrearage', '欠费'), ('lock', '欠费锁定')], default='normal', help_text='欠费状态下存储桶读写锁定管控情况', max_length=16, verbose_name='过期欠费管控情况'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='situation_time',
            field=models.DateTimeField(blank=True, default=None, help_text='欠费管控开始时间', null=True, verbose_name='管控情况时间'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='task_status',
            field=models.CharField(choices=[('created', '创建成功'), ('creating', '正在创建中'), ('failed', '创建失败')], default='created', max_length=16, verbose_name='创建状态'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='situation',
            field=models.CharField(choices=[('normal', '正常'), ('arrearage', '欠费'), ('lock', '欠费锁定')], default='normal', help_text='欠费状态下存储桶读写锁定管控情况', max_length=16, verbose_name='过期欠费管控情况'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='situation_time',
            field=models.DateTimeField(blank=True, default=None, help_text='欠费管控开始时间', null=True, verbose_name='管控情况时间'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='task_status',
            field=models.CharField(choices=[('created', '创建成功'), ('creating', '正在创建中'), ('failed', '创建失败')], default='created', max_length=16, verbose_name='创建状态'),
        ),
    ]
