# Generated by Django 4.2.5 on 2023-11-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20231102_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectsservice',
            name='data_center',
        ),
    ]
