# Generated by Django 3.2.13 on 2023-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20230410_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='object_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='桶对象数量'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='stats_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='桶资源统计时间'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='storage_size',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='桶存储容量'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='tag',
            field=models.CharField(blank=True, choices=[('', '无'), ('special', '专项')], default='', max_length=32, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='object_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='桶对象数量'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='stats_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='桶资源统计时间'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='storage_size',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='桶存储容量'),
        ),
        migrations.AddField(
            model_name='bucketarchive',
            name='tag',
            field=models.CharField(blank=True, choices=[('', '无'), ('special', '专项')], default='', max_length=32, verbose_name='标签'),
        ),
    ]
