# Generated by Django 3.2.13 on 2023-06-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20230413_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsservice',
            name='loki_tag',
            field=models.CharField(blank=True, default='', help_text='服务单元在Loki访问日志中对应的对象存储集群标识，用于计量网络流量、请求量等信息时标识对应关系', max_length=128, verbose_name='对应loki日志中集群标识'),
        ),
    ]
