# Generated by Django 4.2.9 on 2024-03-21 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_price_scan_host_price_scan_web'),
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponapply',
            name='order',
            field=models.ForeignKey(blank=True, default=None, help_text='为某个订单申请资源券，审批通过后自动支付订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.order', verbose_name='申请订单'),
        ),
    ]
