# Generated by Django 4.2.9 on 2024-02-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_delete_payorgnazition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcouponpaymenthistory',
            name='refund_history',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.refundrecord', verbose_name='退款记录'),
        ),
    ]
