# Generated by Django 4.2.16 on 2024-12-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_cashcouponpaymenthistory_refund_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcoupon',
            name='order_id',
            field=models.CharField(blank=True, default='', help_text='适用范围为指定订单时，指定订单编号', max_length=64, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='use_scope',
            field=models.CharField(choices=[('service', '服务单元'), ('order', '指定订单')], default='service', max_length=16, verbose_name='使用范围'),
        ),
    ]
