# Generated by Django 4.2.16 on 2025-01-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_cashcoupon_order_id_cashcoupon_use_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcoupon',
            name='derive_type',
            field=models.CharField(choices=[('other', '其他'), ('trial', '试用'), ('staff', '内部员工')], default='other', max_length=16, verbose_name='来源类型'),
        ),
    ]
