# Generated by Django 4.2.9 on 2024-05-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0012_delete_applyorganization'),
        # ('netbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('telephone', models.CharField(default='', max_length=16, verbose_name='电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱地址')),
                ('address', models.CharField(blank=True, default='', help_text='详细的联系地址', max_length=255, verbose_name='联系地址')),
                ('creation_time', models.DateTimeField(blank=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, verbose_name='更新时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '03_机构二级对象联系人',
                'verbose_name_plural': '03_机构二级对象联系人',
                'db_table': 'net_manage_contact_person',
                'ordering': ('-creation_time',),
            },
        ),
        migrations.CreateModel(
            name='OrgVirtualObject',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注信息')),
                ('contacts', models.ManyToManyField(blank=True, db_constraint=False, db_table='net_manage_org_obj_contacts', related_name='+', to='app_net_manage.contactperson', verbose_name='机构二级对象联系人')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.datacenter', verbose_name='机构')),
            ],
            options={
                'verbose_name': '02_机构二级',
                'verbose_name_plural': '02_机构二级',
                'db_table': 'net_manage_org_virt_obj',
                'ordering': ('-creation_time',),
            },
        ),
    ]
