# Generated by Django 4.2.9 on 2024-05-30 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_net_manage', '0002_copy_tables_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetManageUserRole',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ordinary', '普通用户'), ('admin', '网管管理员')], max_length=16, verbose_name='网管管理角色')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '01_综合网管用户角色和权限',
                'verbose_name_plural': '01_综合网管用户角色和权限',
                'db_table': 'net_manage_user_role',
                'ordering': ('-creation_time',),
            },
        ),
    ]
