# Generated by Django 4.2.9 on 2024-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_net_manage', '0003_netmanageuserrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetIPAccessWhiteList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_value', models.CharField(help_text='192.168.1.1、 192.168.1.1/24、192.168.1.66 - 192.168.1.100', max_length=100, verbose_name='IP')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络管理IP访问白名单',
                'verbose_name_plural': '网络管理IP访问白名单',
                'db_table': 'net_ipaccesswhitelist',
                'ordering': ['-creation_time'],
            },
        ),
    ]
