# Generated by Django 3.1.7 on 2021-03-31 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_userquota_due_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applyment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyquota',
            name='approve_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_apply_quota', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='company',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='申请人单位'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='资源到期时间'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='user_quota',
            field=models.OneToOneField(default=None, help_text='资源配额申请审批通过后生成的对应的用户资源配额', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_quota', to='service.userquota', verbose_name='用户资源配额'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='approve_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='status',
            field=models.CharField(choices=[('wait', '待审批'), ('pass', '审批通过'), ('reject', '拒绝'), ('cancel', '取消申请')], default='wait', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='applyservice',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
