# Generated by Django 3.1.7 on 2021-04-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_userquota_due_time'),
        ('applyment', '0002_auto_20210331_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyquota',
            name='expiration_time',
        ),
        migrations.AddField(
            model_name='applyquota',
            name='deleted',
            field=models.BooleanField(default=False, help_text='选中为删除', verbose_name='删除'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, help_text='审批通过后到配额到期期间的时长，单位天', verbose_name='申请使用时长(天)'),
        ),
        migrations.AddField(
            model_name='applyquota',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_apply_quota_set', to='service.serviceconfig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='approve_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_apply_quota', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='status',
            field=models.CharField(choices=[('wait', '待审批'), ('pending', '审批中'), ('pass', '审批通过'), ('reject', '拒绝'), ('cancel', '取消申请')], default='wait', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='applyquota',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_apply_quota_set', to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
    ]
