# Generated by Django 3.1.7 on 2021-05-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyment', '0003_auto_20210402_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyService',
        ),
    ]
