# Generated by Django 4.2.9 on 2024-07-30 06:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_arrearserver_arrearbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='s_snapshot_count',
            field=models.IntegerField(default=0, verbose_name='云主机快照数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='s_snapshot_prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='云主机快照预付费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='scan_host_count',
            field=models.IntegerField(default=0, verbose_name='Host安全扫描数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='scan_prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='安全扫描预付费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='scan_web_count',
            field=models.IntegerField(default=0, verbose_name='Web安全扫描数'),
        ),
    ]
