# Generated by Django 4.2.5 on 2023-09-25 02:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_bucketstatsmonthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='site_count',
            field=models.IntegerField(default=0, verbose_name='本月站点监控任务数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='site_days',
            field=models.FloatField(blank=True, default=0, help_text='所有站点监控任务总监控天数', verbose_name='监控总天数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='site_tamper_days',
            field=models.FloatField(blank=True, default=0, help_text='所有站点监控任务总防篡改监控天数', verbose_name='防篡改监控总天数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='site_original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='站点监控计费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='site_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='站点监控付费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='site_payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='站点监控应付金额'),
        ),
    ]
