# Generated by Django 4.2.9 on 2024-01-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_objectsservice_monitor_task_id'),
        ('servers', '0003_server_img_release_server_img_release_version_and_more'),
        ('report', '0004_monthlyreport_site_count_monthlyreport_site_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrearServer',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(blank=True, default='', max_length=36, verbose_name='云主机ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='云主机服务单元')),
                ('ipv4', models.CharField(default='', max_length=128, verbose_name='IPV4')),
                ('vcpus', models.IntegerField(default=0, verbose_name='虚拟CPU数')),
                ('ram', models.IntegerField(default=0, verbose_name='内存GiB')),
                ('image', models.CharField(default='', max_length=255, verbose_name='镜像系统名称')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式')),
                ('server_creation', models.DateTimeField(verbose_name='云主机创建时间')),
                ('server_expire', models.DateTimeField(blank=True, default=None, null=True, verbose_name='云主机过期时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='云主机备注')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', help_text='个人云主机的拥有者，或者vo组云主机的创建者', max_length=128, verbose_name='用户名')),
                ('vo_id', models.CharField(blank=True, default='', max_length=36, verbose_name='VO组ID')),
                ('vo_name', models.CharField(blank=True, default='', max_length=256, verbose_name='VO组名')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所有者类型')),
                ('balance_amount', models.DecimalField(decimal_places=2, help_text='用户个人余额，或者VO组余额', max_digits=10, verbose_name='所有者的余额')),
                ('date', models.DateField(help_text='查询欠费云主机数据采样日期', verbose_name='数据日期')),
                ('creation_time', models.DateTimeField(verbose_name='判定为欠费的时间')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servers.serviceconfig', verbose_name='云主机服务单元')),
            ],
            options={
                'verbose_name': '欠费的云主机',
                'verbose_name_plural': '欠费的云主机',
                'db_table': 'report_arrear_server',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='ArrearBucket',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.CharField(max_length=36, verbose_name='存储桶ID')),
                ('bucket_name', models.CharField(max_length=73, verbose_name='存储桶名称')),
                ('service_name', models.CharField(max_length=255, verbose_name='存储服务单元')),
                ('size_byte', models.BigIntegerField(default=0, help_text='byte', verbose_name='存储容量(Byte)')),
                ('object_count', models.BigIntegerField(blank=True, default=0, verbose_name='桶对象数量')),
                ('bucket_creation', models.DateTimeField(verbose_name='存储桶创建时间')),
                ('situation', models.CharField(choices=[('normal', '正常'), ('arrearage', '欠费'), ('arrears-lock', '欠费锁定读写'), ('lock', '锁定读写'), ('lock-write', '锁定写(只读)')], default='normal', help_text='欠费状态下存储桶读写锁定管控情况', max_length=16, verbose_name='过期欠费管控情况')),
                ('situation_time', models.DateTimeField(blank=True, default=None, help_text='欠费管控开始时间', null=True, verbose_name='管控情况时间')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('date', models.DateField(help_text='查询欠费存储桶数据采样日期', verbose_name='数据日期')),
                ('creation_time', models.DateTimeField(verbose_name='判定为欠费的时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='存储桶备注')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.objectsservice', verbose_name='存储服务单元')),
            ],
            options={
                'verbose_name': '欠费的存储桶',
                'verbose_name_plural': '欠费的存储桶',
                'db_table': 'report_arrear_bucket',
                'ordering': ['-creation_time'],
            },
        ),
    ]
