# Generated by Django 3.2.5 on 2022-03-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meter', '计费'), ('prepaid', '预付费'), ('refund', '退款')], max_length=16, verbose_name='账单类型')),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('prepaid', '已支付'), ('cancelled', '作废')], max_length=16, verbose_name='账单状态')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('order_id', models.CharField(blank=True, default='', max_length=36, verbose_name='订单ID')),
                ('resource_type', models.CharField(choices=[('vm', '云主机'), ('disk', '云硬盘'), ('bucket', '存储桶')], max_length=16, verbose_name='资源类型')),
                ('service_id', models.CharField(blank=True, default='', max_length=36, verbose_name='服务ID')),
                ('instance_id', models.CharField(default='', max_length=36, verbose_name='资源实例ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('vo_id', models.CharField(blank=True, default='', max_length=36, verbose_name='VO组ID')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所有者类型')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 'bill',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='VoPointAccount',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='金额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vo', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vo.virtualorganization')),
            ],
            options={
                'verbose_name': 'VO组账户',
                'verbose_name_plural': 'VO组账户',
                'db_table': 'vo_point_account',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPointAccount',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='金额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'user_point_account',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(blank=True, default='', help_text='user id or vo id', max_length=36, verbose_name='付款人ID')),
                ('payer_name', models.CharField(blank=True, default='', help_text='username or vo name', max_length=255, verbose_name='付款人名称')),
                ('payer_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='付款人类型')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('before_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付前余额')),
                ('after_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付后余额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('type', models.CharField(choices=[('recharge', '充值'), ('payment', '支付'), ('refund', '退款')], max_length=16, verbose_name='支付类型')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注信息')),
                ('bill', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.bill')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment_history',
                'ordering': ['-payment_time'],
            },
        ),
    ]
