# Generated by Django 3.2.13 on 2022-06-21 06:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCoupon',
            fields=[
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expiration_time', models.DateTimeField(verbose_name='过期时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='编码')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('status', models.CharField(choices=[('wait', '未领取'), ('available', '有效'), ('cancelled', '作废'), ('deleted', '删除')], default='wait', max_length=16, verbose_name='状态')),
                ('granted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='领取/发放时间')),
                ('owner_type', models.CharField(blank=True, choices=[('user', '用户'), ('vo', 'VO组'), ('', '未知')], default='', max_length=16, verbose_name='所属类型')),
                ('_coupon_code', models.CharField(db_column='coupon_code', max_length=64, verbose_name='券密码')),
            ],
            options={
                'verbose_name': '代金券',
                'verbose_name_plural': '代金券',
                'db_table': 'cash_coupon',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='CashCouponActivity',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expiration_time', models.DateTimeField(verbose_name='过期时间')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('grant_total', models.IntegerField(default=0, verbose_name='发放总数量')),
                ('granted_count', models.IntegerField(default=0, verbose_name='已发放数量')),
                ('grant_status', models.CharField(choices=[('wait', '待发放'), ('grant', '发放中'), ('completed', '发放完毕')], default='wait', max_length=16, verbose_name='发放状态')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='描述信息')),
                ('creator', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '代金券活动/模板',
                'verbose_name_plural': '代金券活动/模板',
                'db_table': 'cash_coupon_activity',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='CashCouponPaymentHistory',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('before_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付前余额')),
                ('after_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付后余额')),
            ],
            options={
                'verbose_name': '代金券扣费记录',
                'verbose_name_plural': '代金券扣费记录',
                'db_table': 'cash_coupon_payment',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='PayApp',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='应用名称')),
                ('app_url', models.CharField(blank=True, default='', max_length=256, verbose_name='应用网址')),
                ('app_desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='应用描述')),
                ('rsa_public_key', models.CharField(blank=True, default='', max_length=2000, verbose_name='RSA公钥')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('unaudited', '未审核'), ('normal', '正常'), ('ban', '禁止')], default='unaudited', max_length=16, verbose_name='应用状态')),
            ],
            options={
                'verbose_name': '支付应用APP',
                'verbose_name_plural': '支付应用APP',
                'db_table': 'app',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_account', models.CharField(blank=True, default='', help_text='用户或VO余额ID, 及可能支持的其他账户', max_length=36, verbose_name='付款账户')),
                ('payment_method', models.CharField(choices=[('balance', '余额'), ('coupon', '代金卷'), ('balance+coupon', '余额+代金卷')], default='balance', max_length=16, verbose_name='付款方式')),
                ('executor', models.CharField(blank=True, default='', help_text='记录此次支付交易是谁执行完成的', max_length=128, verbose_name='交易执行人')),
                ('payer_id', models.CharField(blank=True, default='', help_text='user id or vo id', max_length=36, verbose_name='付款人ID')),
                ('payer_name', models.CharField(blank=True, default='', help_text='username or vo name', max_length=255, verbose_name='付款人名称')),
                ('payer_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='付款人类型')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('before_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付前余额')),
                ('after_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付后余额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('type', models.CharField(choices=[('recharge', '充值'), ('payment', '支付'), ('refund', '退款')], max_length=16, verbose_name='支付类型')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注信息')),
                ('order_id', models.CharField(blank=True, default='', max_length=36, verbose_name='订单ID')),
                ('resource_type', models.CharField(choices=[('vm', '云主机'), ('disk', '云硬盘'), ('bucket', '存储桶')], default='vm', max_length=16, verbose_name='资源类型')),
                ('service_id', models.CharField(blank=True, default='', max_length=36, verbose_name='服务ID')),
                ('instance_id', models.CharField(default='', help_text='云主机，硬盘id，存储桶名称', max_length=64, verbose_name='资源实例ID')),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='代金券或者抵扣金额', max_digits=10, verbose_name='券金额')),
                ('subject', models.CharField(default='', max_length=256, verbose_name='标题')),
                ('app_id', models.CharField(blank=True, default='', max_length=36, verbose_name='应用ID')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment_history',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='VoPointAccount',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='金额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vo', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vo.virtualorganization')),
            ],
            options={
                'verbose_name': 'VO组账户',
                'verbose_name_plural': 'VO组账户',
                'db_table': 'vo_point_account',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPointAccount',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='金额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'user_point_account',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payer_id'], name='idx_payer_id'),
        ),
        migrations.AddField(
            model_name='cashcouponpaymenthistory',
            name='cash_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.cashcoupon'),
        ),
        migrations.AddField(
            model_name='cashcouponpaymenthistory',
            name='payment_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.paymenthistory'),
        ),
        migrations.AddField(
            model_name='cashcouponactivity',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='适用服务'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.cashcouponactivity', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='适用服务'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='vo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='VO组'),
        ),
    ]
