# Generated by Django 3.2.13 on 2022-06-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashcoupon',
            name='service',
        ),
        migrations.RemoveField(
            model_name='cashcouponactivity',
            name='service',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='service_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='app_service_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='APP服务ID'),
        ),
        migrations.CreateModel(
            name='PayOrgnazition',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='英文名称')),
                ('abbreviation', models.CharField(default='', max_length=64, verbose_name='简称')),
                ('independent_legal_person', models.BooleanField(default=True, verbose_name='是否独立法人单位')),
                ('country', models.CharField(default='', max_length=128, verbose_name='国家/地区')),
                ('city', models.CharField(default='', max_length=128, verbose_name='城市')),
                ('postal_code', models.CharField(default='', max_length=32, verbose_name='邮政编码')),
                ('address', models.CharField(default='', max_length=256, verbose_name='单位地址')),
                ('creation_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间')),
                ('desc', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('logo_url', models.CharField(blank=True, default='', max_length=256, verbose_name='LOGO url')),
                ('certification_url', models.CharField(blank=True, default='', max_length=256, verbose_name='机构认证代码url')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='纬度')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'db_table': 'pay_orgnazition',
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='PayAppService',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='服务名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='服务英文名称')),
                ('resources', models.CharField(default='', max_length=128, verbose_name='服务提供的资源')),
                ('desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='服务描述')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('unaudited', '未审核'), ('normal', '正常'), ('ban', '禁止')], default='unaudited', max_length=16, verbose_name='服务状态')),
                ('contact_person', models.CharField(blank=True, default='', max_length=128, verbose_name='联系人名称')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='联系人邮箱')),
                ('contact_telephone', models.CharField(blank=True, default='', max_length=16, verbose_name='联系人电话')),
                ('contact_fixed_phone', models.CharField(blank=True, default='', max_length=16, verbose_name='联系人固定电话')),
                ('contact_address', models.CharField(blank=True, default='', max_length=256, verbose_name='联系人地址')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='纬度')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bill.payapp', verbose_name='应用APP')),
                ('orgnazition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bill.payorgnazition', verbose_name='机构|组织')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '应用APP子服务',
                'verbose_name_plural': '应用APP子服务',
                'db_table': 'app_service',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='app_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.payappservice', verbose_name='适用服务'),
        ),
        migrations.AddField(
            model_name='cashcouponactivity',
            name='app_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.payappservice', verbose_name='适用服务'),
        ),
    ]
