# Generated by Django 3.2.5 on 2022-03-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='executor',
            field=models.CharField(blank=True, default='', help_text='记录此次支付交易是谁执行完成的', max_length=128, verbose_name='交易执行人'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_account',
            field=models.CharField(blank=True, default='', help_text='用户或VO余额ID, 及可能支持的其他账户', max_length=36, verbose_name='付款账户'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('balance', '余额')], default='balance', max_length=16, verbose_name='付款方式'),
        ),
    ]
