# Generated by Django 3.2.5 on 2022-05-16 07:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
        ('bill', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='coupon_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='代金券或者抵扣金额', max_digits=10, verbose_name='券金额'),
        ),
        migrations.CreateModel(
            name='CashCouponPaymentHistory',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('before_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付前余额')),
                ('after_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付后余额')),
                ('cash_coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.cashcoupon')),
                ('payment_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.paymenthistory')),
            ],
            options={
                'verbose_name': '代金券扣费记录',
                'verbose_name_plural': '代金券扣费记录',
                'db_table': 'cash_coupon_payment',
                'ordering': ['-creation_time'],
            },
        ),
    ]
