# Generated by Django 3.2.5 on 2022-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20220329_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='bill',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='instance_id',
            field=models.CharField(default='', help_text='云主机，硬盘id，存储桶名称', max_length=64, verbose_name='资源实例ID'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='resource_type',
            field=models.CharField(choices=[('vm', '云主机'), ('disk', '云硬盘'), ('bucket', '存储桶')], default='vm', max_length=16, verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='service_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='服务ID'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
