# Generated by Django 3.2.13 on 2022-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20220516_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayApp',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='应用名称')),
                ('app_url', models.CharField(blank=True, default='', max_length=256, verbose_name='应用网址')),
                ('app_desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='应用描述')),
                ('rsa_public_key', models.CharField(blank=True, default='', max_length=2000, verbose_name='RSA公钥')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('unaudited', '未审核'), ('normal', '正常'), ('ban', '禁止')], default='unaudited', max_length=16, verbose_name='应用状态')),
            ],
            options={
                'verbose_name': '支付应用APP',
                'verbose_name_plural': '支付应用APP',
                'db_table': 'app',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='app_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='应用ID'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='subject',
            field=models.CharField(default='', max_length=256, verbose_name='标题'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payer_id', 'payer_name'], name='idx_payer_type_name'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
    ]
