# Generated by Django 3.2.13 on 2022-11-16 03:17

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20220704_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBill',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', help_text='用户或VO余额ID, 及可能支持的其他账户', max_length=36, verbose_name='付款账户')),
                ('subject', models.CharField(default='', max_length=256, verbose_name='标题')),
                ('trade_type', models.CharField(choices=[('payment', '支付'), ('recharge', '充值'), ('refund', '退款')], max_length=16, verbose_name='交易类型')),
                ('trade_id', models.CharField(help_text='支付、退款、充值ID', max_length=36, verbose_name='交易id')),
                ('amounts', models.DecimalField(decimal_places=2, help_text='16.66, -8.88', max_digits=10, verbose_name='金额')),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='代金券或者抵扣金额', max_digits=10, verbose_name='券金额')),
                ('after_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易后余额')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注信息')),
                ('owner_id', models.CharField(blank=True, default='', help_text='user id or vo id', max_length=36, verbose_name='所属人ID')),
                ('owner_name', models.CharField(blank=True, default='', help_text='username or vo name', max_length=255, verbose_name='所属人名称')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所属人类型')),
                ('app_service_id', models.CharField(blank=True, default='', max_length=36, verbose_name='APP服务ID')),
                ('app_id', models.CharField(blank=True, default='', max_length=36, verbose_name='应用ID')),
            ],
            options={
                'verbose_name': '交易流水账单',
                'verbose_name_plural': '交易流水账单',
                'db_table': 'transaction_bill',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='after_payment',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='before_payment',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='type',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payable_amounts',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='需付金额'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('wait', '等待支付'), ('success', '支付成功'), ('error', '支付失败'), ('closed', '交易关闭')], default='wait', max_length=16, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='status_desc',
            field=models.CharField(default='', max_length=255, verbose_name='支付状态描述'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='支付时间'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
        migrations.AddIndex(
            model_name='transactionbill',
            index=models.Index(fields=['owner_id'], name='idx_owner_id'),
        ),
        migrations.AddIndex(
            model_name='transactionbill',
            index=models.Index(fields=['trade_id'], name='idx_trade_id'),
        ),
    ]
