# Generated by Django 4.2.5 on 2023-10-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_contacts_datacenter_province_datacenter_contacts'),
        ('bill', '0003_remove_payappservice_orgnazition'),
    ]

    operations = [
        migrations.AddField(
            model_name='payappservice',
            name='orgnazition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.datacenter', verbose_name='机构|组织'),
        ),
    ]
