# Generated by Django 4.2.5 on 2023-11-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_payappservice_orgnazition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcoupon',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
    ]
