# Generated by Django 3.2.13 on 2022-11-17 07:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20221116_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, default='', max_length=36, verbose_name='支付交易记录ID')),
                ('out_order_id', models.CharField(blank=True, default='', max_length=36, verbose_name='外部订单编号')),
                ('out_refund_id', models.CharField(blank=True, default='', max_length=64, verbose_name='外部退款单编号')),
                ('refund_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='退款原因')),
                ('total_amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款对应的交易订单总金额')),
                ('refund_amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申请退款金额')),
                ('real_refund', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际退款金额')),
                ('coupon_refund', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='代金券或者优惠抵扣金额，此金额不退', max_digits=10, verbose_name='代金券退款金额')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('success_time', models.DateTimeField(default=None, null=True, verbose_name='退款成功时间')),
                ('status', models.CharField(choices=[('wait', '等待退款'), ('success', '退款成功'), ('error', '退款失败'), ('closed', '交易关闭')], default='wait', max_length=16, verbose_name='退款状态')),
                ('status_desc', models.CharField(default='', max_length=255, verbose_name='退款状态描述')),
                ('remark', models.CharField(default='', max_length=256, verbose_name='备注信息')),
                ('app_service_id', models.CharField(blank=True, default='', max_length=36, verbose_name='APP服务ID')),
                ('app_id', models.CharField(blank=True, default='', max_length=36, verbose_name='应用ID')),
                ('in_account', models.CharField(blank=True, default='', help_text='用户或VO余额ID, 及可能支持的其他账户', max_length=36, verbose_name='入账账户')),
                ('owner_id', models.CharField(blank=True, default='', help_text='user id or vo id', max_length=36, verbose_name='所属人ID')),
                ('owner_name', models.CharField(blank=True, default='', help_text='username or vo name', max_length=255, verbose_name='所属人名称')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所属人类型')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'db_table': 'refund_record',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['trade_id'], name='idx_refund_trade_id'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['out_refund_id'], name='idx_refund_out_refund_id'),
        ),
    ]
