# Generated by Django 3.2.13 on 2022-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20220609_0635'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='idx_payer_type_name',
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='idx_order_id',
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payer_id'], name='idx_payer_id'),
        ),
    ]
