# Generated by Django 3.2.13 on 2022-12-22 03:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20221117_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbill',
            name='out_trade_no',
            field=models.CharField(default='', help_text='支付订单号、退款单号', max_length=64, verbose_name='外部交易编号'),
        ),
        migrations.AddField(
            model_name='transactionbill',
            name='trade_amounts',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='余额+券金额', max_digits=10, verbose_name='交易总金额'),
        ),
    ]
