# Generated by Django 3.2.13 on 2023-01-10 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0006_auto_20221222_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payappservice',
            name='user',
        ),
        migrations.AddField(
            model_name='payappservice',
            name='users',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='pay_app_service_users', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
    ]
