# Generated by Django 3.2.13 on 2023-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20230110_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payappservice',
            name='service',
        ),
        migrations.AddField(
            model_name='payappservice',
            name='service_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='对应的服务单元ID'),
        ),
    ]
