# Generated by Django 3.2.13 on 2023-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20230110_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_channel', models.CharField(choices=[('manual', '人工充值'), ('wechat', '微信支付'), ('alipay', '支付宝')], default='manual', max_length=16, verbose_name='交易渠道')),
                ('out_trade_no', models.CharField(blank=True, default='', max_length=64, verbose_name='外部交易编号')),
                ('channel_account', models.CharField(blank=True, default='', max_length=64, verbose_name='交易渠道账户编号')),
                ('channel_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易渠道费用')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值总金额')),
                ('receipt_amount', models.DecimalField(decimal_places=2, help_text='交易渠道中我方账户实际收到的款项', max_digits=10, verbose_name='实收金额'),),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('success_time', models.DateTimeField(default=None, null=True, verbose_name='充值成功时间')),
                ('status', models.CharField(choices=[('wait', '待充值'), ('success', '支付成功'), ('error', '支付失败'), ('closed', '交易关闭'), ('complete', '充值完成')], default='wait', max_length=16, verbose_name='充值状态')),
                ('status_desc', models.CharField(default='', max_length=255, verbose_name='充值状态描述')),
                ('in_account', models.CharField(blank=True, default='', help_text='用户或VO余额ID, 及可能支持的其他账户', max_length=36, verbose_name='入账账户')),
                ('owner_id', models.CharField(blank=True, default='', help_text='user id or vo id', max_length=36, verbose_name='所属人ID')),
                ('owner_name', models.CharField(blank=True, default='', help_text='username or vo name', max_length=255, verbose_name='所属人名称')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所属人类型')),
                ('remark', models.CharField(default='', max_length=256, verbose_name='备注信息')),
                ('executor', models.CharField(blank=True, default='', help_text='记录此次支付交易是谁执行完成的', max_length=128, verbose_name='交易执行人')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'wallet_recharge',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['owner_id'], name='idx_recharge_owner_id'),
        ),
    ]
