# Generated by Django 3.2.13 on 2023-03-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_auto_20230306_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcoupon',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='发放人'),
        ),
    ]
