# Generated by Django 3.2.13 on 2023-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_cashcoupon_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcoupon',
            name='balance_notice_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='余额不足通知时间'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='expire_notice_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期通知时间'),
        ),
    ]
