# Generated by Django 3.2.13 on 2023-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_auto_20230330_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrecord',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='记录此次支付交易是谁执行完成的', max_length=128, verbose_name='交易操作人'),
        ),
        migrations.AddField(
            model_name='transactionbill',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='记录此次支付交易是谁执行完成的', max_length=128, verbose_name='交易操作人'),
        ),
    ]
