# Generated by Django 3.2.5 on 2022-03-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0007_auto_20211119_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringServer',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=36, verbose_name='云服务器ID')),
                ('date', models.DateField(help_text='计量的资源使用量的所属日期', verbose_name='日期')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('vo_id', models.CharField(blank=True, default='', max_length=36, verbose_name='VO组ID')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=8, verbose_name='所有者类型')),
                ('cpu_hours', models.FloatField(blank=True, default=0, help_text='云服务器的CPU Hour数', verbose_name='CPU Hour')),
                ('ram_hours', models.FloatField(blank=True, default=0, help_text='云服务器的内存Gib Hour数', verbose_name='内存GiB Hour')),
                ('disk_hours', models.FloatField(blank=True, default=0, help_text='云服务器的系统盘Gib Hour数', verbose_name='系统盘GiB Hour')),
                ('public_ip_hours', models.FloatField(blank=True, default=0, help_text='云服务器的公网IP Hour数', verbose_name='IP Hour')),
                ('snapshot_hours', models.FloatField(blank=True, default=0, help_text='云服务器的快照小时数', verbose_name='快照GiB Hour')),
                ('upstream', models.FloatField(blank=True, default=0, help_text='云服务器的上行流量Gib', verbose_name='上行流量GiB')),
                ('downstream', models.FloatField(blank=True, default=0, help_text='云服务器的下行流量Gib', verbose_name='下行流量GiB')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], max_length=16, verbose_name='云服务器付费方式')),
                ('service', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.serviceconfig', verbose_name='服务')),
            ],
            options={
                'verbose_name': '云服务器资源计量',
                'verbose_name_plural': '云服务器资源计量',
                'db_table': 'metering_server',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='meteringserver',
            constraint=models.UniqueConstraint(fields=('date', 'server_id'), name='unique_date_server'),
        ),
    ]
