# Generated by Django 3.2.5 on 2022-05-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('service', '0001_initial'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringserver',
            name='service',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='payment_history',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.paymenthistory', verbose_name='支付记录'),
        ),
    ]
