# Generated by Django 3.2.5 on 2022-05-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('service', '0001_initial'),
        ('metering', '0002_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='service',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.objectsservice', verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='payment_history',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.paymenthistory', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='service',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='服务'),
        ),
        migrations.AddConstraint(
            model_name='meteringserver',
            constraint=models.UniqueConstraint(fields=('date', 'server_id'), name='unique_date_server'),
        ),
        migrations.AddConstraint(
            model_name='meteringobjectstorage',
            constraint=models.UniqueConstraint(fields=('date', 'service_id', 'user_id', 'bucket_name'), name='unique_date_bucket'),
        ),
        migrations.AddConstraint(
            model_name='meteringdisk',
            constraint=models.UniqueConstraint(fields=('date', 'disk_id'), name='unique_date_disk'),
        ),
    ]
