# Generated by Django 3.2.5 on 2022-03-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('metering', '0002_auto_20220308_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringObjectStorage',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=36, verbose_name='用户ID')),
                ('bucket_id', models.CharField(max_length=36, verbose_name='存储桶ID')),
                ('bucket_name', models.CharField(max_length=63, verbose_name='存储桶名称')),
                ('date', models.DateField(help_text='计量的资源使用量的所属日期', verbose_name='日期')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('storage', models.FloatField(blank=True, default=0, help_text='存储桶的存储容量GiB', verbose_name='存储容量GiB')),
                ('downstream', models.FloatField(blank=True, default=0, help_text='存储桶的下行流量GiB', verbose_name='下行流量GiB')),
                ('replication', models.FloatField(blank=True, default=0, help_text='存储桶的同步流量GiB', verbose_name='同步流量GiB')),
                ('get_request', models.IntegerField(default=0, help_text='存储桶的get请求次数', verbose_name='get请求次数')),
                ('put_request', models.IntegerField(default=0, help_text='存储桶的put请求次数', verbose_name='put请求次数')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], max_length=16, verbose_name='对象存储付费方式')),
                ('service', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storage.objectsservice', verbose_name='服务')),
            ],
            options={
                'verbose_name': '对象存储资源计量',
                'verbose_name_plural': '对象存储资源计量',
                'db_table': 'metering_object_storage',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='meteringobjectstorage',
            constraint=models.UniqueConstraint(fields=('date', 'service_id', 'user_id', 'bucket_name'), name='unique_date_bucket'),
        ),
    ]
