# Generated by Django 3.2.13 on 2022-09-07 08:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20220901_0252'),
        ('metering', '0002_auto_20220818_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatementObjectStorage',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='计费金额')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='应付金额')),
                ('trade_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='实付金额')),
                ('payment_status', models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('cancelled', '作废')], default='unpaid', max_length=16, verbose_name='支付状态')),
                ('payment_history_id', models.CharField(blank=True, default='', max_length=36, verbose_name='支付记录ID')),
                ('date', models.DateField(help_text='资源使用计量计费的日期', verbose_name='计费日期')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '对象存储日结算单',
                'verbose_name_plural': '对象存储日结算单',
                'db_table': 'daily_statement_storage',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='meteringobjectstorage',
            name='unique_date_bucket',
        ),
        migrations.RemoveField(
            model_name='meteringobjectstorage',
            name='bucket_id',
        ),
        migrations.RemoveField(
            model_name='meteringobjectstorage',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='storage_bucket_id',
            field=models.CharField(default='', help_text='对象存储中间件存储桶实例id', max_length=36, verbose_name='存储桶实例ID'),
        ),
        migrations.AddConstraint(
            model_name='meteringobjectstorage',
            constraint=models.UniqueConstraint(fields=('date', 'storage_bucket_id'), name='unique_date_bucket'),
        ),
        migrations.AddField(
            model_name='dailystatementobjectstorage',
            name='service',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.objectsservice', verbose_name='对象存储服务单元'),
        ),
    ]
