# Generated by Django 3.2.5 on 2022-03-29 09:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('metering', '0003_auto_20220309_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringdisk',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='计费金额'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='payment_history',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.paymenthistory', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('cancelled', '作废')], default='unpaid', max_length=16, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='trade_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='交易金额'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='计费金额'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='payment_history',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.paymenthistory', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('cancelled', '作废')], default='unpaid', max_length=16, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='trade_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='交易金额'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='计费金额'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='payment_history',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.paymenthistory', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('cancelled', '作废')], default='unpaid', max_length=16, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='trade_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='交易金额'),
        ),
    ]
