# Generated by Django 4.2.5 on 2023-09-18 03:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringMonitorWebsite',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='计费金额')),
                ('trade_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='应付金额')),
                ('daily_statement_id', models.CharField(default='', max_length=36, verbose_name='日结算单ID')),
                ('website_id', models.CharField(max_length=36, verbose_name='监控站点ID')),
                ('website_name', models.CharField(max_length=255, verbose_name='监控站点名称')),
                ('user_id', models.CharField(blank=True, max_length=36, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('date', models.DateField(help_text='计量的资源使用量的所属日期', verbose_name='日期')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('hours', models.FloatField(blank=True, default=0, help_text='小时数', verbose_name='监控小时数')),
                ('detection_count', models.PositiveIntegerField(default=0, verbose_name='探测次数')),
                ('tamper_resistant_count', models.PositiveIntegerField(default=0, help_text='防篡改探测次数，记录站点监控是否设置防篡改监控服务', verbose_name='是否防篡改')),
                ('security_count', models.PositiveIntegerField(default=0, help_text='安全扫描次数，记录站点监控是否设置安全扫描服务', verbose_name='是否安全扫描')),
            ],
            options={
                'verbose_name': '站点监控计量',
                'verbose_name_plural': '站点监控计量',
                'db_table': 'metering_monitor_website',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='meteringmonitorwebsite',
            constraint=models.UniqueConstraint(fields=('website_id', 'date'), name='unique_website_date'),
        ),
    ]
