# Generated by Django 3.2.5 on 2022-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringdisk',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='meteringdisk',
            name='vo_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VO组名'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='meteringserver',
            name='vo_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VO组名'),
        ),
    ]
