# Generated by Django 3.2.13 on 2022-06-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0004_auto_20220530_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteringdisk',
            name='payment_history',
            field=models.CharField(default='', max_length=36, verbose_name='支付记录ID'),
        ),
        migrations.AlterField(
            model_name='meteringobjectstorage',
            name='payment_history',
            field=models.CharField(default='', max_length=36, verbose_name='支付记录ID'),
        ),
        migrations.AlterField(
            model_name='meteringserver',
            name='payment_history',
            field=models.CharField(default='', max_length=36, verbose_name='支付记录ID'),
        ),
    ]
