# Generated by Django 3.2.13 on 2023-06-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0004_meteringobjectstorage_storage_byte'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='billed_network_flow',
            field=models.FloatField(blank=True, default=0, help_text='存储桶的计费流量GiB', verbose_name='计费流量GiB'),
        ),
        migrations.AddField(
            model_name='meteringobjectstorage',
            name='unbilled_network_flow',
            field=models.FloatField(blank=True, default=0, help_text='存储桶的非计费流量GiB', verbose_name='非计费流量GiB'),
        ),
    ]
