# Generated by Django 3.2.13 on 2022-06-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0005_auto_20220621_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteringdisk',
            old_name='payment_history',
            new_name='payment_history_id',
        ),
        migrations.RenameField(
            model_name='meteringobjectstorage',
            old_name='payment_history',
            new_name='payment_history_id',
        ),
        migrations.RenameField(
            model_name='meteringserver',
            old_name='payment_history',
            new_name='payment_history_id',
        ),
    ]
