# Generated by Django 4.2.9 on 2024-04-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimedTaskLook',
        ),
    ]
