# Generated by Django 4.2.9 on 2024-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_couponapply_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponapply',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='联系方式'),
        ),
    ]
