# Generated by Django 4.2.9 on 2024-05-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alert', '0001_squashed_0001_initial_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertLifetimeModel',
        ),
        migrations.AlterModelOptions(
            name='alertmodel',
            options={'ordering': ['-creation'], 'verbose_name': '进行中告警', 'verbose_name_plural': '进行中告警'},
        ),
        migrations.AlterModelOptions(
            name='prealertmodel',
            options={'ordering': ['-creation'], 'verbose_name': '预处理告警', 'verbose_name_plural': '预处理告警'},
        ),
        migrations.AlterModelOptions(
            name='resolvedalertmodel',
            options={'ordering': ['-creation'], 'verbose_name': '已恢复告警', 'verbose_name_plural': '已恢复告警'},
        ),
        migrations.AlterUniqueTogether(
            name='alertworkorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='order',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_alert.alertworkorder', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='recovery',
            field=models.PositiveBigIntegerField(null=True, verbose_name='恢复时间'),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='status',
            field=models.CharField(choices=[('firing', '进行中'), ('resolved', '已恢复')], default='firing', max_length=20, verbose_name='告警状态'),
        ),
        migrations.AddField(
            model_name='prealertmodel',
            name='order',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_alert.alertworkorder', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='prealertmodel',
            name='recovery',
            field=models.PositiveBigIntegerField(null=True, verbose_name='恢复时间'),
        ),
        migrations.AddField(
            model_name='prealertmodel',
            name='status',
            field=models.CharField(choices=[('firing', '进行中'), ('resolved', '已恢复')], default='firing', max_length=20, verbose_name='告警状态'),
        ),
        migrations.AddField(
            model_name='resolvedalertmodel',
            name='order',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_alert.alertworkorder', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='resolvedalertmodel',
            name='recovery',
            field=models.PositiveBigIntegerField(null=True, verbose_name='恢复时间'),
        ),
        migrations.AddField(
            model_name='resolvedalertmodel',
            name='status',
            field=models.CharField(choices=[('firing', '进行中'), ('resolved', '已恢复')], default='resolved', max_length=20, verbose_name='告警状态'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='creation',
            field=models.FloatField(db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警预结束时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='severity',
            field=models.CharField(choices=[('warning', '警告'), ('error', '错误'), ('critical', '严重错误')], db_index=True, max_length=50, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='type',
            field=models.CharField(choices=[('metric', '指标类'), ('log', '日志类'), ('webmonitor', '网站监控')], db_index=True, max_length=64, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='alertworkorder',
            name='status',
            field=models.CharField(choices=[('误报', '误报'), ('已完成', '已完成'), ('无需处理', '无需处理')], default='无需处理', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='creation',
            field=models.FloatField(db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警预结束时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='severity',
            field=models.CharField(choices=[('warning', '警告'), ('error', '错误'), ('critical', '严重错误')], db_index=True, max_length=50, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='type',
            field=models.CharField(choices=[('metric', '指标类'), ('log', '日志类'), ('webmonitor', '网站监控')], db_index=True, max_length=64, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='creation',
            field=models.FloatField(db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警预结束时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='severity',
            field=models.CharField(choices=[('warning', '警告'), ('error', '错误'), ('critical', '严重错误')], db_index=True, max_length=50, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='type',
            field=models.CharField(choices=[('metric', '指标类'), ('log', '日志类'), ('webmonitor', '网站监控')], db_index=True, max_length=64, verbose_name='类型'),
        ),
        migrations.RemoveField(
            model_name='alertworkorder',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alertworkorder',
            name='collect',
        ),
    ]
