# Generated by Django 4.2.9 on 2024-04-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alert', '0002_scriptflagmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptFlagModel',
        ),
    ]
