# Generated by Django 4.2.9 on 2024-04-28 06:55

from django.db import migrations, models, connection
import django.db.models.deletion


def clear_order_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('DELETE FROM `alert_work_order`;')


def do_nothing(apps, schema_editor):
    print('do nothing')


class Migration(migrations.Migration):
    dependencies = [
        ('app_alert', '0003_delete_scriptflagmodel'),
    ]

    operations = [
        migrations.RunPython(clear_order_table, reverse_code=do_nothing),
        migrations.AlterField(
            model_name='alertworkorder',
            name='creation',
            field=models.PositiveIntegerField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='alertworkorder',
            name='modification',
            field=models.PositiveIntegerField(null=True, verbose_name='更新时间'),
        ),
    ]
