# Generated by Django 4.2.9 on 2024-07-10 09:02

from django.db import migrations, transaction, connection


def drop_ticket_handler_table(apps, schema_editor):
    with transaction.atomic(savepoint=False):
        with connection.cursor() as cursor:
            cursor.execute('DROP TABLE IF EXISTS `alert_ticket_handler`;')


class Migration(migrations.Migration):

    dependencies = [
        ('app_alert', '0004_remove_alertticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertservice',
            name='users',
        ),
        # migrations.RemoveField(
        #     model_name='alertticket',
        #     name='handlers',
        # ),
        migrations.RemoveField(
            model_name='alertticket',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='alertticket',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='alertworkorder',
            name='creator',
        ),
        # migrations.RemoveField(
        #     model_name='serviceadminuser',
        #     name='service',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceadminuser',
        #     name='userprofile',
        # ),
        migrations.RemoveField(
            model_name='servicelog',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='users',
        ),
        migrations.RemoveField(
            model_name='servicemetric',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicemetric',
            name='users',
        ),
        # migrations.RemoveField(
        #     model_name='tickethandler',
        #     name='ticket',
        # ),
        # migrations.RemoveField(
        #     model_name='tickethandler',
        #     name='user',
        # ),
        migrations.RemoveField(
            model_name='ticketresolution',
            name='category',
        ),
        migrations.RemoveField(
            model_name='alertmodel',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='prealertmodel',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='resolvedalertmodel',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='AlertMonitorJobServer',
        ),
        migrations.DeleteModel(
            name='AlertService',
        ),
        migrations.DeleteModel(
            name='AlertTicket',
        ),
        migrations.DeleteModel(
            name='AlertWorkOrder',
        ),
        migrations.DeleteModel(
            name='ServiceAdminUser',
        ),
        migrations.DeleteModel(
            name='ServiceLog',
        ),
        migrations.DeleteModel(
            name='ServiceMetric',
        ),
        # migrations.DeleteModel(
        #     name='TicketHandler',
        # ),
        migrations.RunSQL(sql='DROP TABLE IF EXISTS `alert_ticket_handler`;'),
        migrations.DeleteModel(
            name='TicketResolution',
        ),
        migrations.DeleteModel(
            name='TicketResolutionCategory',
        ),
    ]
