# Generated by Django 4.2.9 on 2024-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alert', '0005_alter_alertworkorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlifetimemodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警结束时间'),
        ),
        migrations.AlterField(
            model_name='alertlifetimemodel',
            name='start',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警开始时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='count',
            field=models.PositiveBigIntegerField(default=1, verbose_name='累加条数'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='creation',
            field=models.PositiveBigIntegerField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警结束时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='first_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='首次通知时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='last_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='上次通知时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='modification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='start',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='告警开始时间'),
        ),
        migrations.AlterField(
            model_name='alertworkorder',
            name='creation',
            field=models.PositiveBigIntegerField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='alertworkorder',
            name='modification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='timestamp',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='通知时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='count',
            field=models.PositiveBigIntegerField(default=1, verbose_name='累加条数'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='creation',
            field=models.PositiveBigIntegerField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警结束时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='first_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='首次通知时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='last_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='上次通知时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='modification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='prealertmodel',
            name='start',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='告警开始时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='count',
            field=models.PositiveBigIntegerField(default=1, verbose_name='累加条数'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='creation',
            field=models.PositiveBigIntegerField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='end',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='告警结束时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='first_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='首次通知时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='last_notification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='上次通知时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='modification',
            field=models.PositiveBigIntegerField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='resolvedalertmodel',
            name='start',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='告警开始时间'),
        ),
    ]
