# Generated by Django 4.2.9 on 2024-05-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alert', '0006_alter_alertlifetimemodel_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertWhiteListModel',
        ),
    ]
