# Generated by Django 4.2.9 on 2024-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_price_vm_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='描述'),
        ),
    ]
