# Generated by Django 4.2.4 on 2023-08-29 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vo', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='vo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='VO组'),
        ),
        migrations.AddField(
            model_name='bucketmonthlyreport',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddConstraint(
            model_name='bucketmonthlyreport',
            constraint=models.UniqueConstraint(fields=('report_date', 'bucket_id'), name='unique_report_date_bucket'),
        ),
    ]
