# Generated by Django 3.2.13 on 2023-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='period_end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='月度报表周期结束时间'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='period_start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='月度报表周期开始时间'),
        ),
    ]
