# Generated by Django 3.2.13 on 2023-07-17 00:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20230524_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_count',
            field=models.IntegerField(default=0, verbose_name='本月度云硬盘数'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='云硬盘计费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='云硬盘按量应付金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_postpaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='云硬盘按量后付费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='云硬盘订购预付费金额'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='disk_size_days',
            field=models.FloatField(blank=True, default=0, help_text='云硬盘的容量大小GiB Day数', verbose_name='云硬盘容量GiB*Day'),
        ),
    ]
