# Generated by Django 4.2.5 on 2023-10-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('telephone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱地址')),
                ('address', models.CharField(help_text='详细的联系地址', max_length=255, verbose_name='联系地址')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机构联系人',
                'verbose_name_plural': '机构联系人',
                'db_table': 'contacts',
                'ordering': ('-creation_time',),
            },
        ),
        migrations.AddField(
            model_name='datacenter',
            name='province',
            field=models.CharField(default='', max_length=128, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='contacts',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='data_center_contacts', related_name='+', to='service.contacts', verbose_name='机构联系人'),
        ),
    ]
