# Generated by Django 4.2.5 on 2023-11-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20231101_0610'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='serviceconfig',
        #     name='data_center',
        # ),
    ]
