# Generated by Django 4.2.7 on 2023-11-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_serviceconfig_data_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdatacenter',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='数据中心备注'),
        ),
    ]
