# Generated by Django 4.2.9 on 2024-05-22 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_squashed_0010_remove_datacenter_endpoint_compute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgdatacenteradminuser',
            options={'ordering': ['-join_time'], 'verbose_name': '数据中心管理员', 'verbose_name_plural': '数据中心管理员'},
        ),
        migrations.AddField(
            model_name='orgdatacenteradminuser',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
        migrations.AddField(
            model_name='orgdatacenteradminuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('ops', '运维')], default='admin', max_length=16, verbose_name='角色'),
        ),
    ]
