# Generated by Django 4.2.9 on 2024-05-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_orgdatacenteradminuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyOrganization',
        ),
    ]
