# Generated by Django 4.2.9 on 2024-11-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_orgdatacenter_map_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunYuanService',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服务名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='服务英文名称')),
                ('endpoint_url', models.CharField(help_text='http(s)://{hostname}:{port}/', max_length=255, verbose_name='服务地址url')),
                ('username', models.CharField(blank=True, default='', help_text='用于此服务认证的用户名', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('enable', '服务中'), ('disable', '停止服务'), ('deleted', '删除')], default='enable', max_length=32, verbose_name='服务状态')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='纬度')),
                ('sort_weight', models.IntegerField(default=0, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('version', models.CharField(blank=True, default='', help_text='服务当前的版本', max_length=32, verbose_name='版本号')),
                ('version_update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='版本号更新时间')),
                ('org_data_center', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '坤元服务单元',
                'verbose_name_plural': '坤元服务单元',
                'db_table': 'service_kunyuan',
                'ordering': ['sort_weight'],
            },
        ),
    ]
