# Generated by Django 4.2.9 on 2024-05-14 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    # replaces = [('app_netflow', '0001_initial'), ('app_netflow', '0002_alter_chartmodel_remark_and_more'),
    #             ('app_netflow', '0003_menumodel_name'), ('app_netflow', '0004_rolemodel'),
    #             ('app_netflow', '0005_alter_chartmodel_options_alter_menumodel_options_and_more'),
    #             ('app_netflow', '0006_remove_rolemodel_charts_remove_rolemodel_users_and_more'),
    #             ('app_netflow', '0007_menu2chart_menu2member_menumodel_menu2member_menu_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_weight', models.IntegerField(default=-1, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('band_width', models.PositiveIntegerField(default=0, verbose_name='带宽')),
                ('class_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('class_uuid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device_ip', models.CharField(default='', max_length=255, verbose_name='IP')),
                ('if_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('if_alias', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='别名')),
                ('instance_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instance_uuid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modification', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('port_name', models.CharField(default='', max_length=255, verbose_name='端口')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '元素管理',
                'verbose_name_plural': '元素管理',
                'db_table': 'netflow_chart',
                'ordering': ['sort_weight'],
                'unique_together': {('device_ip', 'port_name')},
            },
        ),
        migrations.CreateModel(
            name='Menu2Chart',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='自定义标题')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('sort_weight', models.IntegerField(blank=True, default=-1, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_netflow.chartmodel', verbose_name='组元素')),
            ],
            options={
                'verbose_name': '组-元素',
                'verbose_name_plural': '组-元素',
                'db_table': 'netflow_menu2chart',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='Menu2Member',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ordinary', '组员'), ('group-admin', '组管理员')], default='ordinary', max_length=16, verbose_name='角色')),
                ('inviter', models.CharField(editable=False, max_length=128, verbose_name='邀请人')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modification', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='组成员')),
            ],
            options={
                'verbose_name': '组-成员',
                'verbose_name_plural': '组-成员',
                'db_table': 'netflow_menu2member',
                'ordering': ['creation', 'modification'],
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('level', models.IntegerField(default=-1, editable=False, verbose_name='组级别')),
                ('sort_weight', models.IntegerField(default=-1, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('charts', models.ManyToManyField(related_name='menu_set', related_query_name='menu', through='app_netflow.Menu2Chart', to='app_netflow.chartmodel', verbose_name='流量图表集')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', related_query_name='children', to='app_netflow.menumodel', verbose_name='上级菜单')),
                ('members', models.ManyToManyField(related_name='netflow_group_set', related_query_name='netflow_group', through='app_netflow.Menu2Member', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '组结构管理',
                'verbose_name_plural': '组结构管理',
                'db_table': 'netflow_menu',
                'ordering': ['level', 'sort_weight'],
                'unique_together': {('father', 'name')},
            },
        ),
        migrations.AddField(
            model_name='menu2member',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_netflow.menumodel', verbose_name='组'),
        ),
        migrations.AddField(
            model_name='menu2chart',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_netflow.menumodel', verbose_name='组'),
        ),
        migrations.CreateModel(
            name='GlobalAdminModel',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('super-admin', '超级管理员')], default='admin', max_length=16, verbose_name='角色')),
                ('inviter', models.CharField(default='', editable=False, max_length=128, verbose_name='邀请人')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modification', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '01_网络流量全局用户角色',
                'verbose_name_plural': '01_网络流量全局用户角色',
                'db_table': 'netflow_globaladmin',
                'ordering': ['creation', 'modification'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='menu2member',
            unique_together={('menu', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='menu2chart',
            unique_together={('menu', 'chart')},
        ),
    ]
