# Generated by Django 4.2.9 on 2024-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_netflow', '0002_netflowlogentrymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu2chart',
            name='title',
        ),
        migrations.AddField(
            model_name='menu2chart',
            name='admin_remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='管理员备注'),
        ),
        migrations.AlterField(
            model_name='menu2chart',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
    ]
