# Generated by Django 2.2.13 on 2020-06-11 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.SmallIntegerField(choices=[(1, 'VPN使用方法')], default=1, verbose_name='主题')),
                ('lang', models.SmallIntegerField(choices=[(1, '中文'), (2, '英文')], default=1, verbose_name='语言')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('summary', models.CharField(blank=True, default='', help_text='可以为空', max_length=255, verbose_name='概述')),
                ('author', models.CharField(blank=True, default='', max_length=255, verbose_name='作者')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='正文内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('enable', models.BooleanField(default=False, help_text='是否发布可见，默认不发布可见，一般在文章编辑完成后再发布可见', verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VPNAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20, verbose_name='VPN口令')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_auth', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'VPN口令',
                'verbose_name_plural': 'VPN口令',
                'db_table': 'vpn_auth',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='idx_article_title'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['create_time'], name='idx_article_create_time'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('topic', 'lang')},
        ),
    ]
