# Generated by Django 4.2.9 on 2024-09-02 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_net_ipam', '0002_copy_tables_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4Supernet',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.PositiveIntegerField(verbose_name='起始地址')),
                ('end_address', models.PositiveIntegerField(verbose_name='截止地址')),
                ('mask_len', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(32)], verbose_name='子网掩码长度')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('status', models.CharField(choices=[('out-warehouse', '未入库'), ('in-warehouse', '已入库'), ('split', '已拆分')], default='out-warehouse', max_length=16, verbose_name='状态')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('asn', models.PositiveIntegerField(default=0, verbose_name='AS编码')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('operator', models.CharField(blank=True, default='', max_length=128, verbose_name='操作人')),
                ('used_ip_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='已分配IP数')),
                ('total_ip_count', models.PositiveIntegerField(blank=True, verbose_name='IP总数')),
            ],
            options={
                'verbose_name': 'IPv4地址超网段',
                'verbose_name_plural': 'IPv4地址超网段',
                'db_table': 'net_ipam_ipv4_supernet',
                'ordering': ('-creation_time',),
            },
        ),
    ]
