# Generated by Django 4.2.9 on 2024-09-13 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_net_ipam', '0003_ipv4supernet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIPv4Range',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.PositiveIntegerField(verbose_name='起始地址')),
                ('end_address', models.PositiveIntegerField(verbose_name='截止地址')),
                ('mask_len', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(32)], verbose_name='子网掩码长度')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('asn', models.PositiveIntegerField(default=0, verbose_name='AS编号')),
                ('org_name', models.CharField(blank=True, default='', max_length=128, verbose_name='机构')),
                ('country', models.CharField(blank=True, default='', max_length=64, verbose_name='国家')),
                ('city', models.CharField(blank=True, default='', max_length=128, verbose_name='城市')),
                ('operator', models.CharField(blank=True, default='', max_length=128, verbose_name='操作人')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IPv4外部地址段',
                'verbose_name_plural': 'IPv4外部地址段',
                'db_table': 'net_ipam_external_ipv4',
                'ordering': ('-creation_time',),
            },
        ),
    ]
