# Generated by Django 3.2.5 on 2022-05-11 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='service_set', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='applyvmservice',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.datacenter', verbose_name='数据中心'),
        ),
        migrations.AddField(
            model_name='applyvmservice',
            name='service',
            field=models.OneToOneField(blank=True, default=None, help_text='服务接入申请审批通过后生成的对应的接入服务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_service', to='service.serviceconfig', verbose_name='接入服务'),
        ),
        migrations.AddField(
            model_name='applyvmservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
        migrations.AddField(
            model_name='applyorganization',
            name='data_center',
            field=models.OneToOneField(blank=True, default=None, help_text='机构加入申请审批通过后对应的机构', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_data_center', to='service.datacenter', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='applyorganization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
    ]
