# Generated by Django 3.1.5 on 2021-02-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_squashed_0006_userquota_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrivateQuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('private_ip_total', models.IntegerField(default=0, verbose_name='总私网IP数')),
                ('private_ip_used', models.IntegerField(default=0, verbose_name='已用私网IP数')),
                ('public_ip_total', models.IntegerField(default=0, verbose_name='总公网IP数')),
                ('public_ip_used', models.IntegerField(default=0, verbose_name='已用公网IP数')),
                ('vcpu_total', models.IntegerField(default=0, verbose_name='总CPU核数')),
                ('vcpu_used', models.IntegerField(default=0, verbose_name='已用CPU核数')),
                ('ram_total', models.IntegerField(default=0, verbose_name='总内存大小(MB)')),
                ('ram_used', models.IntegerField(default=0, verbose_name='已用内存大小(MB)')),
                ('disk_size_total', models.IntegerField(default=0, verbose_name='总硬盘大小(GB)')),
                ('disk_size_used', models.IntegerField(default=0, verbose_name='已用硬盘大小(GB)')),
                ('enable', models.BooleanField(default=True, help_text='选中，资源配额生效；未选中，无法申请分中心资源', verbose_name='有效状态')),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_private_quota', to='service.serviceconfig', verbose_name='接入服务')),
            ],
            options={
                'verbose_name': '接入服务的私有资源配额',
                'verbose_name_plural': '接入服务的私有资源配额',
                'db_table': 'service_private_quota',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceShareQuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('private_ip_total', models.IntegerField(default=0, verbose_name='总私网IP数')),
                ('private_ip_used', models.IntegerField(default=0, verbose_name='已用私网IP数')),
                ('public_ip_total', models.IntegerField(default=0, verbose_name='总公网IP数')),
                ('public_ip_used', models.IntegerField(default=0, verbose_name='已用公网IP数')),
                ('vcpu_total', models.IntegerField(default=0, verbose_name='总CPU核数')),
                ('vcpu_used', models.IntegerField(default=0, verbose_name='已用CPU核数')),
                ('ram_total', models.IntegerField(default=0, verbose_name='总内存大小(MB)')),
                ('ram_used', models.IntegerField(default=0, verbose_name='已用内存大小(MB)')),
                ('disk_size_total', models.IntegerField(default=0, verbose_name='总硬盘大小(GB)')),
                ('disk_size_used', models.IntegerField(default=0, verbose_name='已用硬盘大小(GB)')),
                ('enable', models.BooleanField(default=True, help_text='选中，资源配额生效；未选中，无法申请分中心资源', verbose_name='有效状态')),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_share_quota', to='service.serviceconfig', verbose_name='接入服务')),
            ],
            options={
                'verbose_name': '接入服务的分享资源配额',
                'verbose_name_plural': '接入服务的分享资源配额',
                'db_table': 'service_share_quota',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='datacentersharequota',
            name='data_center',
        ),
        migrations.AddField(
            model_name='userquota',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quota', to='service.serviceconfig', verbose_name='适用服务'),
        ),
        migrations.DeleteModel(
            name='DataCenterPrivateQuota',
        ),
        migrations.DeleteModel(
            name='DataCenterShareQuota',
        ),
    ]
