# Generated by Django 3.1.5 on 2021-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210201_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['creation_time'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AlterModelOptions(
            name='serviceconfig',
            options={'ordering': ['-add_time'], 'verbose_name': '服务接入配置', 'verbose_name_plural': '服务接入配置'},
        ),
        migrations.AlterModelOptions(
            name='serviceprivatequota',
            options={'ordering': ['-creation_time'], 'verbose_name': '接入服务的私有资源配额', 'verbose_name_plural': '接入服务的私有资源配额'},
        ),
        migrations.AlterModelOptions(
            name='servicesharequota',
            options={'ordering': ['-creation_time'], 'verbose_name': '接入服务的分享资源配额', 'verbose_name_plural': '接入服务的分享资源配额'},
        ),
        migrations.AlterModelOptions(
            name='userquota',
            options={'ordering': ['-creation_time'], 'verbose_name': '用户资源配额', 'verbose_name_plural': '用户资源配额'},
        ),
        migrations.AddField(
            model_name='datacenter',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='endpoint_compute',
            field=models.CharField(blank=True, default=None, help_text='http(s)://{hostname}:{port}/', max_length=255, null=True, unique=True, verbose_name='计算服务地址url'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='endpoint_monitor',
            field=models.CharField(blank=True, default=None, help_text='http(s)://{hostname}:{port}/', max_length=255, null=True, unique=True, verbose_name='检测报警服务地址url'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='endpoint_object',
            field=models.CharField(blank=True, default=None, help_text='http(s)://{hostname}:{port}/', max_length=255, null=True, unique=True, verbose_name='存储服务地址url'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='endpoint_vms',
            field=models.CharField(blank=True, default=None, help_text='http(s)://{hostname}:{port}/', max_length=255, null=True, unique=True, verbose_name='云主机服务地址url'),
        ),
        migrations.AddField(
            model_name='serviceprivatequota',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='servicesharequota',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='userquota',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceprivatequota',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicesharequota',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
