# Generated by Django 3.2.4 on 2021-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210617_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorganization',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='applyvmservice',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='服务英文名称'),
        ),
    ]
