# Generated by Django 3.2.13 on 2023-02-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceconfig_pay_app_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='endpoint_url',
            field=models.CharField(help_text='http(s)://{hostname}:{port}/', max_length=255, verbose_name='服务地址url'),
        ),
    ]
