# Generated by Django 4.2.5 on 2023-11-01 06:10

from django.db import migrations
from service.models import ServiceConfig, OrgDataCenter


def servive_org_data_center(apps, schema_editor):
    # service_model = apps.get_model("service", "ServiceConfig")
    services = ServiceConfig.objects.select_related('data_center').all()
    ok_count = 0
    skip_count = 0
    for sv in services:
        org = sv.data_center
        if org is None:
            skip_count += 1
            continue

        # 机构下没有数据中心就创建一个默认数据中心
        odc = OrgDataCenter.objects.filter(organization_id=org.id).first()
        if odc is None:
            odc = OrgDataCenter(name=f'数据中心-{org.name}', name_en='', organization_id=org.id)
            odc.save(force_insert=True)

        sv.org_data_center_id = odc.id
        sv.save(update_fields=['org_data_center_id'])
        ok_count += 1

    print(f'Changed server service ForeignKey to OrgDataCenter OK，ok={ok_count}, skip={skip_count}')


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_orgdatacenter_serviceconfig_org_data_center'),
    ]

    operations = [
        migrations.RunPython(servive_org_data_center, reverse_code=None),
    ]
