# Generated by Django 3.2.13 on 2023-04-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_serviceconfig_endpoint_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['-sort_weight'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AddField(
            model_name='datacenter',
            name='sort_weight',
            field=models.IntegerField(default=0, help_text='值越大排序越靠前', verbose_name='排序权重'),
        ),
    ]
