# Generated by Django 2.2.16 on 2020-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20201113_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
