# Generated by Django 3.2.5 on 2021-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_applyquota_result_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorganization',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='applyorganization',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='经度'),
        ),
    ]
