# Generated by Django 3.1.7 on 2021-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_userquota_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='due_time',
        ),
        migrations.AddField(
            model_name='userquota',
            name='duration_days',
            field=models.IntegerField(blank=True, default=365, help_text='使用此配额创建的资源的有效使用时长', verbose_name='资源使用时长'),
        ),
    ]
