# Generated by Django 3.2.5 on 2022-04-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20211119_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='vo',
        ),
        migrations.DeleteModel(
            name='ApplyQuota',
        ),
        migrations.DeleteModel(
            name='UserQuota',
        ),
    ]
