# Generated by Django 4.2.7 on 2023-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_orgdatacenter_remark'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='serviceconfig',
        #     name='only_admin_visible',
        #     field=models.BooleanField(default=False, verbose_name='仅管理员可见'),
        # ),
    ]
