# Generated by Django 3.2.13 on 2023-06-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20230522_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='disk_available',
            field=models.BooleanField(default=False, verbose_name='提供云硬盘服务'),
        ),
    ]
