# Generated by Django 4.2.9 on 2024-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_serviceconfig_only_admin_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdatacenter',
            name='log_monitor_url',
            field=models.CharField(blank=True, default='', help_text='如果填写有效网址会自动创建对应的站点监控任务，格式为 http(s)://example.cn/', max_length=255, verbose_name='日志聚合系统监控网址'),
        ),
        migrations.AddField(
            model_name='orgdatacenter',
            name='log_task_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='记录为日志聚合系统监控网址创建的站点监控任务的ID', max_length=36, verbose_name='日志聚合系统监控任务ID'),
        ),
        migrations.AddField(
            model_name='orgdatacenter',
            name='metric_monitor_url',
            field=models.CharField(blank=True, default='', help_text='如果填写有效网址会自动创建对应的站点监控任务，格式为 http(s)://example.cn/', max_length=255, verbose_name='指标监控系统监控网址'),
        ),
        migrations.AddField(
            model_name='orgdatacenter',
            name='metric_task_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='记录为指标监控系统监控地址创建的站点监控任务的ID', max_length=36, verbose_name='指标监控系统监控任务ID'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='monitor_task_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='记录为服务单元创建的站点监控任务的ID', max_length=36, verbose_name='服务单元对应监控任务ID'),
        ),
    ]
