# Generated by Django 3.2 on 2021-06-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210603_0250_squashed_0010_auto_20210603_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyvmservice',
            old_name='data_center',
            new_name='organization',
        ),
    ]
