# Generated by Django 4.2.7 on 2023-11-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='img_release',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统发行版'),
        ),
        migrations.AddField(
            model_name='server',
            name='img_release_version',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统发行版版本'),
        ),
        migrations.AddField(
            model_name='server',
            name='img_sys_arch',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统架构'),
        ),
        migrations.AddField(
            model_name='server',
            name='img_sys_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统类型'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='img_release',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统发行版'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='img_release_version',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统发行版版本'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='img_sys_arch',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统架构'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='img_sys_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='镜像系统类型'),
        ),
    ]
