# Generated by Django 4.2.9 on 2024-05-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vo', '0001_initial'),
        ('servers', '0005_serviceconfig_version_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSnapshot',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='快照名称')),
                ('instance_id', models.CharField(help_text='各接入服务单元中快照的ID', max_length=128, verbose_name='快照实例ID')),
                ('size', models.IntegerField(default=0, verbose_name='容量大小GiB')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
                ('start_time', models.DateTimeField(help_text='快照资源使用量计量开始时间', verbose_name='计量开始时间')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式')),
                ('classification', models.CharField(choices=[('personal', '个人的'), ('vo', 'VO组的')], default='personal', help_text='标识快照属于申请者个人的，还是vo组的', max_length=16, verbose_name='快照归属类型')),
                ('email_lasttime', models.DateTimeField(blank=True, default=None, help_text='记录上次发邮件的时间，邮件通知用户快照即将到期', null=True, verbose_name='上次发送邮件时间')),
                ('deleted', models.BooleanField(default=False, help_text='选中表示已删除', verbose_name='删除状态')),
                ('deleted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('deleted_user', models.CharField(blank=True, default='', max_length=128, verbose_name='删除人')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='snapshot_set', to='servers.server', verbose_name='归属云主机')),
                ('service', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servers.serviceconfig', verbose_name='服务单元')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('vo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '云主机快照',
                'verbose_name_plural': '云主机快照',
                'db_table': 'servers_serversnapshot',
                'ordering': ['-creation_time'],
                'indexes': [models.Index(fields=['server_id'], name='idx_snapshot_server_id')],
            },
        ),
    ]
