# Generated by Django 4.2.9 on 2024-10-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_serversnapshot_system_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVCloudPermsLog',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', '成功'), ('failed', '失败'), ('invalid', '无效')], default='ok', max_length=16, verbose_name='状态')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('num', models.IntegerField(default=1, verbose_name='尝试次数')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servers.server', verbose_name='归属云主机')),
            ],
            options={
                'verbose_name': 'EVCloud云主机权限同步记录',
                'verbose_name_plural': 'EVCloud云主机权限同步记录',
                'db_table': 'servers_evcloud_perm_log',
                'ordering': ['-creation_time'],
            },
        ),
    ]
