# Generated by Django 4.2.9 on 2024-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_disk_created_user_server_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='server_managed',
            field=models.IntegerField(default=0, help_text='服务单元在本服务中管理的云主机数', verbose_name='本服务在管云主机数'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='server_total',
            field=models.IntegerField(default=0, help_text='服务单元中总的云主机数', verbose_name='服务单元云主机总数'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='server_update_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='云主机数更新时间'),
        ),
    ]
