# Generated by Django 4.2.16 on 2024-12-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_description'),
        ('bill', '0008_cashcoupon_order_id_cashcoupon_use_scope'),
        ('servers', '0010_serviceconfig_server_managed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceOrderDeliverTask',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait', '待执行'), ('in-progress', '执行中'), ('failed', '失败'), ('completed', '完成'), ('cancelled', '作废')], default='wait', max_length=16, verbose_name='状态')),
                ('status_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='状态描述')),
                ('progress', models.CharField(choices=[('ordered', '已订购'), ('coupon', '已发资源券'), ('paid', '已支付'), ('partdeliver', '部分交付'), ('delivered', '已交付')], max_length=16, verbose_name='任务进度')),
                ('submitter_id', models.CharField(max_length=36, verbose_name='提交人id')),
                ('submitter', models.CharField(max_length=128, verbose_name='提交人')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('task_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='任务描述')),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bill.cashcoupon', verbose_name='资源券')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='订单')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.serviceconfig', verbose_name='服务单元')),
            ],
            options={
                'verbose_name': '资源订购交付任务',
                'verbose_name_plural': '资源订购交付任务',
                'db_table': 'servers_res_od_deliver_task',
                'ordering': ['-creation_time'],
            },
        ),
    ]
