# Generated by Django 4.2.16 on 2025-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_resourceorderdelivertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceorderdelivertask',
            name='derive_type',
            field=models.CharField(choices=[('other', '其他'), ('trial', '试用'), ('staff', '内部员工')], default='other', max_length=16, verbose_name='来源类型'),
        ),
    ]
