# Generated by Django 4.2.9 on 2024-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_img_release_server_img_release_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='version',
            field=models.CharField(default='', help_text='服务当前的版本', max_length=32, verbose_name='版本号'),
        ),
    ]
