# Generated by Django 4.2.9 on 2024-05-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_serversnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyVmService',
        ),
    ]
