# Generated by Django 4.2.9 on 2024-08-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_delete_applyvmservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversnapshot',
            name='system_name',
            field=models.CharField(default='', max_length=255, verbose_name='操作系统名称'),
        ),
        migrations.AddField(
            model_name='serversnapshot',
            name='system_release',
            field=models.CharField(default='', max_length=64, verbose_name='操作系统发行版'),
        ),
    ]
