# Generated by Django 4.2.9 on 2024-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimedTaskLock',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('metering', '计量计费'), ('bkt-monthly', '存储桶月度统计'), ('report-monthly', '月度报表'), ('log-time-count', '日志时序统计'), ('req-count', '服务请求量统计'), ('scan', '安全扫描'), ('screen_host_cpuusage', '大屏展示主机CPU使用率'), ('screen_service_stats', '大屏展示服务单元统计数据'), ('alert_email', '告警邮件通知'), ('alert_dingtalk', '告警钉钉通知'), ('scree_user_operate_log', '大屏展示用户操作日志')], max_length=32, verbose_name='定时任务')),
                ('status', models.CharField(choices=[('none', '无'), ('running', '执行中')], default='none', max_length=16, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='执行开始时间')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='执行结束时间')),
                ('host', models.CharField(blank=True, default='', max_length=64, verbose_name='执行任务的节点IP')),
                ('run_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='执行结果描述')),
                ('expire_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='锁定过期时间')),
                ('notify_time', models.DateTimeField(blank=True, default=None, help_text='用于记录邮件通知发送时间，避免重复发送', null=True, verbose_name='锁过期未释放通知时间')),
            ],
            options={
                'verbose_name': '定时任务状态锁',
                'verbose_name_plural': '定时任务状态锁',
                'db_table': 'global_timetasklock',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='timedtasklock',
            constraint=models.UniqueConstraint(fields=('task',), name='unique_lock_task'),
        ),
    ]
