# Generated by Django 4.2.9 on 2024-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('site_name', '站点名称'), ('site_name_en', '站点英文名称'), ('site_front_url', '站点前端地址')], max_length=32, verbose_name='配置名称')),
                ('value', models.CharField(default='', max_length=255, verbose_name='配置内容')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点参数',
                'verbose_name_plural': '站点参数',
                'db_table': 'global_config',
                'ordering': ['creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='globalconfig',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_global_config_name'),
        ),
    ]
