# Generated by Django 4.2.9 on 2024-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[
                    ('site_name', '站点名称'), ('site_name_en', '站点英文名称'), ('site_front_url', '站点前端地址'),
                    ('aai_login_name', 'AAI登录，名称'), ('aai_login_client_callback_url', 'AAI登录，本服务认证回调地址'),
                    ('aai_login_url', 'AAI登录，登录地址'), ('aai_login_token_url', 'AAI登录，token查询地址'),
                    ('aai_login_user_info_url', 'AAI登录，用户信息查询地址'), ('aai_login_client_id', 'AAI登录，客户端id'),
                    ('aai_login_client_secret', 'AAI登录，客户端密钥'),
                    ('aai_jwt_verifying_key', 'AAI JWT认证公钥'),
                    ('prometheus_service_url', 'prometheus服务地址'), ('prometheus_base', 'promtheus基础配置文件'),
                    ('prometheus_blackbox_http', 'promtheus blackbox http 配置文件模板'),
                    ('prometheus_blackbox_tcp', 'promtheus blackbox tcp 配置文件模板'),
                    ('prometheus_exporter_node', 'promtheus exporter node 配置文件'),
                    ('prometheus_exporter_tidb', 'promtheus exporter tidb 配置文件'),
                    ('prometheus_exporter_ceph', 'promtheus exporter ceph 配置文件'),
                    ('sales_customer_service_info', '销售客服人员联系信息'),
                    ('wallet_rsa_private_key', '钱包签名验签RSA密钥对私钥'),
                    ('wallet_rsa_public_key', '钱包签名验签RSA密钥对公钥'),
                ], max_length=32, verbose_name='配置名称')),
                ('value', models.CharField(default='', max_length=255, verbose_name='配置内容')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点参数',
                'verbose_name_plural': '站点参数',
                'db_table': 'global_config',
                'ordering': ['creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='globalconfig',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_global_config_name'),
        ),
    ]
