# Generated by Django 4.2.9 on 2024-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0002_globalconfig_globalconfig_unique_global_config_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccessWhiteList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(choices=[
                    ('screen', '大屏展示'), ('email', '邮件发送API'),
                    ('alert-receiver', '告警接收API'),
                    ('portal', 'Portal门户接口'), ('admin', 'Admin后台'),
                ], help_text='此IP白名单适用的功能模块', max_length=32, verbose_name='功能模块')),
                ('ip_value', models.CharField(help_text='192.168.1.1、 192.168.1.1/24、192.168.1.66 - 192.168.1.100', max_length=100, verbose_name='IP')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'IP访问白名单',
                'verbose_name_plural': 'IP访问白名单',
                'db_table': 'global_ipaccesswhitelist',
                'ordering': ['-creation_time'],
            },
        ),
    ]
