# Generated by Django 4.2.9 on 2024-12-02 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_global', '0004_alter_globalconfig_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标题')),
                ('name_en', models.CharField(max_length=128, verbose_name='英文标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('publish', '发布'), ('revoked', '撤销')], default='draft', max_length=16, verbose_name='状态')),
                ('content', models.TextField(verbose_name='内容')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expire_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
                ('publisher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '站内公告',
                'verbose_name_plural': '站内公告',
                'db_table': 'global_announcement',
                'ordering': ['-creation_time'],
            },
        ),
    ]
