# Generated by Django 4.2.16 on 2024-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_en',
            field=models.TextField(default='', verbose_name='英文内容'),
        ),
    ]
