# Generated by Django 3.2.5 on 2021-09-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_applyquota_result_desc'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorJobServer',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='监控的主机集群名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='监控的主机集群英文名称')),
                ('job_tag', models.CharField(default='', max_length=255, verbose_name='主机集群标签名称')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='monitor.monitorprovider', verbose_name='监控服务配置')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_job_server_set', to='service.serviceconfig', verbose_name='所属的服务')),
            ],
            options={
                'verbose_name': '监控服务器节点',
                'verbose_name_plural': '监控服务器节点',
                'ordering': ['-creation'],
            },
        ),
    ]
