# Generated by Django 3.2.13 on 2022-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorjobceph',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
