# Generated by Django 3.2.13 on 2022-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20221108_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorjobceph',
            name='prometheus',
            field=models.CharField(blank=True, default='', help_text='http(s)://example.cn/', max_length=255, verbose_name='Prometheus接口'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='prometheus',
            field=models.CharField(blank=True, default='', help_text='http(s)://example.cn/', max_length=255, verbose_name='Prometheus接口'),
        ),
        migrations.AddField(
            model_name='monitorjobvideomeeting',
            name='prometheus',
            field=models.CharField(blank=True, default='', help_text='http(s)://example.cn/', max_length=255, verbose_name='Prometheus接口'),
        ),
        migrations.AddField(
            model_name='monitorjobvideomeeting',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='monitorprovider',
            name='bucket_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='存储桶名称'),
        ),
        migrations.AddField(
            model_name='monitorprovider',
            name='bucket_service_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='存储桶所在对象存储服务名称'),
        ),
        migrations.AddField(
            model_name='monitorprovider',
            name='bucket_service_url',
            field=models.CharField(blank=True, default='', help_text='http(s)://example.cn/', max_length=255, verbose_name='存储桶所在对象存储服务地址'),
        ),
        migrations.AddField(
            model_name='monitorprovider',
            name='receive_url',
            field=models.CharField(blank=True, default='', help_text='http(s)://example.cn/', max_length=255, verbose_name='接收接口'),
        ),
        migrations.AddField(
            model_name='monitorprovider',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
