# Generated by Django 3.2.13 on 2022-12-20 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0004_auto_20221108_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorjobceph',
            options={'ordering': ['-sort_weight'], 'verbose_name': 'Ceph监控单元', 'verbose_name_plural': 'Ceph监控单元'},
        ),
        migrations.AlterModelOptions(
            name='monitorjobserver',
            options={'ordering': ['-sort_weight'], 'verbose_name': '服务器监控单元', 'verbose_name_plural': '服务器监控单元'},
        ),
        migrations.RemoveField(
            model_name='monitorjobceph',
            name='service',
        ),
        migrations.RemoveField(
            model_name='monitorjobserver',
            name='service',
        ),
        migrations.AddField(
            model_name='monitorjobceph',
            name='dashboard_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dashboard连接'),
        ),
        migrations.AddField(
            model_name='monitorjobceph',
            name='grafana_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Grafana连接'),
        ),
        migrations.AddField(
            model_name='monitorjobceph',
            name='sort_weight',
            field=models.IntegerField(default=0, help_text='值越大排序越靠前', verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='monitorjobceph',
            name='users',
            field=models.ManyToManyField(db_constraint=False, db_table='monitor_ceph_users', related_name='_monitor_monitorjobceph_users_+', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='dashboard_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dashboard连接'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='grafana_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Grafana连接'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='sort_weight',
            field=models.IntegerField(default=0, help_text='值越大排序越靠前', verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='users',
            field=models.ManyToManyField(db_constraint=False, db_table='monitor_server_users', related_name='_monitor_monitorjobserver_users_+', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
    ]
