# Generated by Django 4.2.5 on 2023-11-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_serviceconfig_data_center_and_more'),
        ('monitor', '0004_alter_monitorwebsite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsite',
            name='org_data_center',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心'),
        ),
        migrations.AddField(
            model_name='monitorjobceph',
            name='org_data_center',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='org_data_center',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心'),
        ),
        migrations.AddField(
            model_name='monitorjobtidb',
            name='org_data_center',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心'),
        ),
    ]
