# Generated by Django 4.2.5 on 2023-11-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20231103_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsite',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='logsite',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='monitorjobceph',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='monitorjobceph',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='monitorjobceph',
            name='service',
        ),
        migrations.RemoveField(
            model_name='monitorjobserver',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='monitorjobserver',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='monitorjobserver',
            name='service',
        ),
        migrations.RemoveField(
            model_name='monitorjobtidb',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='monitorjobtidb',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='monitorjobtidb',
            name='service',
        ),
    ]
