# Generated by Django 3.2.13 on 2023-03-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20230216_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetectionPoint',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='监控探测点名称')),
                ('name_en', models.CharField(default='', max_length=128, verbose_name='监控探测点英文名称')),
                ('creation', models.DateTimeField(verbose_name='创建时间')),
                ('modification', models.DateTimeField(verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('provider', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.monitorprovider', verbose_name='监控查询服务配置信息')),
            ],
            options={
                'verbose_name': '网站监控探测点',
                'verbose_name_plural': '网站监控探测点',
                'db_table': 'website_detection_point',
                'ordering': ['-creation'],
            },
        ),
    ]
