# Generated by Django 3.2.13 on 2023-03-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_websitedetectionpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorwebsiteversion',
            name='provider',
        ),
        migrations.AddField(
            model_name='monitorwebsite',
            name='is_attention',
            field=models.BooleanField(default=False, verbose_name='特别关注'),
        ),
    ]
