# Generated by Django 3.2.13 on 2023-04-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_monitorjobtidb'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorjobtidb',
            name='version',
            field=models.CharField(blank=True, default='', help_text='xx.xx.xx', max_length=32, verbose_name='TiDB版本'),
        ),
    ]
