# Generated by Django 3.2.13 on 2023-05-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20230522_0631'),
        ('monitor', '0011_monitorjobtidb_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorjobceph',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='云主机服务单元'),
        ),
        migrations.AddField(
            model_name='monitorjobserver',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='云主机服务单元'),
        ),
        migrations.AddField(
            model_name='monitorjobtidb',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='云主机服务单元'),
        ),
    ]
