# Generated by Django 3.2.13 on 2023-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20230529_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorwebsite',
            name='hostname',
            field=models.CharField(default='', help_text='hostname:8000', max_length=255, verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='monitorwebsite',
            name='is_tamper_resistant',
            field=models.BooleanField(default=False, verbose_name='防篡改'),
        ),
        migrations.AddField(
            model_name='monitorwebsite',
            name='scheme',
            field=models.CharField(default='', help_text='https|ftps://', max_length=32, verbose_name='协议'),
        ),
        migrations.AddField(
            model_name='monitorwebsite',
            name='uri',
            field=models.CharField(default='', help_text='/a/b?query=123#test', max_length=1024, verbose_name='URI'),
        ),
        migrations.AddField(
            model_name='monitorwebsitetask',
            name='is_tamper_resistant',
            field=models.BooleanField(default=False, verbose_name='防篡改'),
        ),
    ]
