# Generated by Django 3.2.13 on 2023-06-02 09:26
import hashlib
from urllib.parse import urlsplit

from django.db import migrations


def website_to_fill_url_new_fields(apps, schema_editor):
    MonitorWebsite = apps.get_model("monitor", "MonitorWebsite")    # class 'django.db.models.base.ModelBase'
    websites = MonitorWebsite.objects.all()
    for wsite in websites:
        try:
            scheme, netloc, path, query, fragment = urlsplit(wsite.url)
            wsite.scheme = scheme + '://'
            wsite.hostname = netloc

            uri = path if path else '/'
            if uri[:1] != '/':
                uri = '/' + uri

            if query:
                uri = uri + '?' + query
            if fragment:
                uri = uri + '#' + fragment

            wsite.uri = uri
            full_url = wsite.scheme + wsite.hostname + wsite.uri
            wsite.url_hash = hashlib.sha1(full_url.encode(encoding='utf-8')).hexdigest()
        except ValueError:
            print(f'Failed to fill MonitorWebsite({wsite.id}) new fields，Invalid url [{wsite.url}]')
            continue

        wsite.save(update_fields=['scheme', 'hostname', 'uri', 'url_hash'])

    print('Ok Fill fields "scheme"、"hostname"、"uri",', len(websites))


def clear_new_fields(apps, schema_editor):
    MonitorWebsite = apps.get_model("monitor", "MonitorWebsite")
    rows = MonitorWebsite.objects.all().update(scheme='', hostname='', uri='')
    print(f'Ok clear fields "scheme"、"hostname"、"uri", {rows}')


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20230602_0706'),
    ]

    operations = [
        migrations.RunPython(website_to_fill_url_new_fields, reverse_code=clear_new_fields),
    ]
