# Generated by Django 3.2.13 on 2023-07-21 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0008_serviceconfig_disk_available'),
        ('monitor', '0014_auto_20230602_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSiteType',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='对象存储、一体云', max_length=64, unique=True, verbose_name='日志网站类别名称')),
                ('name_en', models.CharField(default='', max_length=128, verbose_name='英文名称')),
                ('sort_weight', models.IntegerField(help_text='值越小排序越靠前', verbose_name='排序值')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modification', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '日志网站类别',
                'verbose_name_plural': '日志网站类别',
                'db_table': 'log_site_type',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='LogSite',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='日志单元站点名称')),
                ('name_en', models.CharField(default='', max_length=128, verbose_name='日志单元英文名称')),
                ('log_type', models.CharField(choices=[('http', 'HTTP'), ('nat', 'NAT')], default='http', max_length=16, verbose_name='日志类型')),
                ('job_tag', models.CharField(default='', help_text='Loki日志中对应的job标识', max_length=64, verbose_name='网站日志单元标识')),
                ('sort_weight', models.IntegerField(help_text='值越小排序越靠前', verbose_name='排序值')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modification', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('organization', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.datacenter', verbose_name='机构')),
                ('provider', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='monitor.monitorprovider', verbose_name='日志数据查询服务提供者')),
                ('site_type', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.logsitetype', verbose_name='站点类别')),
                ('users', models.ManyToManyField(blank=True, db_constraint=False, db_table='log_site_users', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='管理用户')),
            ],
            options={
                'verbose_name': '日志单元站点',
                'verbose_name_plural': '日志单元站点',
                'db_table': 'log_site',
                'ordering': ['sort_weight'],
            },
        ),
    ]
