# Generated by Django 3.2.13 on 2023-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_logsite_logsitetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalReqNum',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_num', models.IntegerField(default=0, verbose_name='服务总请求数')),
                ('until_time', models.DateTimeField(verbose_name='截止到时间')),
                ('creation', models.DateTimeField(verbose_name='创建时间')),
                ('modification', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '一体云和对象存储总请求数',
                'verbose_name_plural': '一体云和对象存储总请求数',
                'db_table': 'total_req_num',
                'ordering': ['creation'],
            },
        ),
    ]
