# Generated by Django 3.2.13 on 2023-08-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_logsitetimereqnum'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logsitetimereqnum',
            index=models.Index(fields=['timestamp'], name='idx_timestamp'),
        ),
    ]
