# Generated by Django 4.2.7 on 2023-12-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_ipv6rangerecord_ipv6range_ipv6address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipv4address',
            name='ip_range',
        ),
    ]
