# Generated by Django 4.2.9 on 2024-01-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_remove_distributionframe_link_org_and_more'),
        ('ipam', '0004_contactperson_orgvirtualobject_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipamuserrole',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='ipamuserrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='IPv4Address',
        ),
        migrations.RemoveField(
            model_name='ipv4range',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='ipv4range',
            name='org_virt_obj',
        ),
        migrations.RemoveField(
            model_name='ipv4rangerecord',
            name='org_virt_obj',
        ),
        migrations.RemoveField(
            model_name='ipv4rangerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='IPv6Address',
        ),
        migrations.RemoveField(
            model_name='ipv6range',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='ipv6range',
            name='org_virt_obj',
        ),
        migrations.RemoveField(
            model_name='ipv6rangerecord',
            name='org_virt_obj',
        ),
        migrations.RemoveField(
            model_name='ipv6rangerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgvirtualobject',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='orgvirtualobject',
            name='organization',
        ),
        migrations.DeleteModel(
            name='ASN',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='IPAMUserRole',
        ),
        migrations.DeleteModel(
            name='IPv4Range',
        ),
        migrations.DeleteModel(
            name='IPv4RangeRecord',
        ),
        migrations.DeleteModel(
            name='IPv6Range',
        ),
        migrations.DeleteModel(
            name='IPv6RangeRecord',
        ),
        migrations.DeleteModel(
            name='OrgVirtualObject',
        ),
    ]
