# Generated by Django 4.2.9 on 2024-06-28 08:09

from django.db import migrations, models, connection, transaction


def do_nothing(apps, schema_editor):
    print('do nothing')


def update_user_fed_admin(apps, schema_editor):
    with transaction.atomic(savepoint=False):
        with connection.cursor() as cursor:
            r = cursor.execute(
                "UPDATE `users_userprofile` SET `is_fed_admin` = 1 WHERE `users_userprofile`.`username` "
                "IN (SELECT U0.`username` FROM `users_userprofile` U0 WHERE LOWER(JSON_UNQUOTE(U0.`role`)) "
                "LIKE LOWER('%federal-admin%'));")

            print(f'[Ok] {r} user update is_fed_admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_email_is_feint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_fed_admin',
            field=models.BooleanField(default=False, verbose_name='联邦管理员'),
        ),
        migrations.RunPython(update_user_fed_admin, reverse_code=do_nothing)
    ]
