# Generated by Django 3.2.5 on 2022-05-11 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcpus', models.IntegerField(default=0, verbose_name='虚拟CPU数')),
                ('ram', models.IntegerField(default=0, verbose_name='内存GiB')),
                ('enable', models.BooleanField(default=True, verbose_name='可用状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '配置样式',
                'verbose_name_plural': '配置样式',
                'db_table': 'flavor',
                'ordering': ['vcpus'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服务器实例名称')),
                ('instance_id', models.CharField(help_text='各接入服务中云主机的ID', max_length=128, verbose_name='云主机实例ID')),
                ('instance_name', models.CharField(blank=True, default='', help_text='各接入服务中云主机的名称', max_length=255, verbose_name='云主机实例名称')),
                ('vcpus', models.IntegerField(default=0, verbose_name='虚拟CPU数')),
                ('ram', models.IntegerField(default=0, verbose_name='内存GiB')),
                ('ipv4', models.CharField(default='', max_length=128, verbose_name='IPV4')),
                ('public_ip', models.BooleanField(default=True, verbose_name='公/私网')),
                ('image', models.CharField(default='', max_length=255, verbose_name='镜像系统名称')),
                ('image_id', models.CharField(default='', max_length=64, verbose_name='镜像系统ID')),
                ('image_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='镜像系统描述')),
                ('default_user', models.CharField(default='', max_length=64, verbose_name='默认登录用户名')),
                ('default_password', models.CharField(blank=True, default='', max_length=255, verbose_name='默认登录密码')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('task_status', models.SmallIntegerField(choices=[(1, '创建成功'), (2, '正在创建中'), (3, '创建失败')], default=1, verbose_name='创建状态')),
                ('center_quota', models.SmallIntegerField(choices=[(1, '私有资源配额'), (2, '共享资源配额')], default=1, verbose_name='服务配额')),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
                ('classification', models.CharField(choices=[('personal', '个人的'), ('vo', 'VO组的')], default='personal', help_text='标识云主机属于申请者个人的，还是vo组的', max_length=16, verbose_name='云主机归属类型')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='云主机资源使用量计量开始时间', verbose_name='计量开始时间')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式')),
                ('azone_id', models.CharField(blank=True, default='', max_length=36, verbose_name='可用区')),
                ('disk_size', models.IntegerField(default=0, verbose_name='系统盘GB')),
                ('lock', models.CharField(choices=[('free', '无锁'), ('lock-delete', '锁定删除'), ('lock-operation', '锁定所有操作，只允许读')], default='free', help_text='加锁锁定云主机，防止误操作', max_length=16, verbose_name='锁')),
                ('email_lasttime', models.DateTimeField(blank=True, default=None, help_text='记录上次发邮件的时间，邮件通知用户配额即将到期', null=True, verbose_name='上次发送邮件时间')),
            ],
            options={
                'verbose_name': '虚拟服务器',
                'verbose_name_plural': '虚拟服务器',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='ServerArchive',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服务器实例名称')),
                ('instance_id', models.CharField(help_text='各接入服务中云主机的ID', max_length=128, verbose_name='云主机实例ID')),
                ('instance_name', models.CharField(blank=True, default='', help_text='各接入服务中云主机的名称', max_length=255, verbose_name='云主机实例名称')),
                ('vcpus', models.IntegerField(default=0, verbose_name='虚拟CPU数')),
                ('ram', models.IntegerField(default=0, verbose_name='内存GiB')),
                ('ipv4', models.CharField(default='', max_length=128, verbose_name='IPV4')),
                ('public_ip', models.BooleanField(default=True, verbose_name='公/私网')),
                ('image', models.CharField(default='', max_length=255, verbose_name='镜像系统名称')),
                ('image_id', models.CharField(default='', max_length=64, verbose_name='镜像系统ID')),
                ('image_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='镜像系统描述')),
                ('default_user', models.CharField(default='', max_length=64, verbose_name='默认登录用户名')),
                ('default_password', models.CharField(blank=True, default='', max_length=255, verbose_name='默认登录密码')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('task_status', models.SmallIntegerField(choices=[(1, '创建成功'), (2, '正在创建中'), (3, '创建失败')], default=1, verbose_name='创建状态')),
                ('center_quota', models.SmallIntegerField(choices=[(1, '私有资源配额'), (2, '共享资源配额')], default=1, verbose_name='服务配额')),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
                ('classification', models.CharField(choices=[('personal', '个人的'), ('vo', 'VO组的')], default='personal', help_text='标识云主机属于申请者个人的，还是vo组的', max_length=16, verbose_name='云主机归属类型')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='云主机资源使用量计量开始时间', verbose_name='计量开始时间')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式')),
                ('azone_id', models.CharField(blank=True, default='', max_length=36, verbose_name='可用区')),
                ('disk_size', models.IntegerField(default=0, verbose_name='系统盘GB')),
                ('server_id', models.CharField(blank=True, default='', help_text='归档服务器的ID', max_length=36, verbose_name='服务器ID')),
                ('deleted_time', models.DateTimeField(verbose_name='删除归档时间')),
                ('archive_type', models.CharField(choices=[('archive', '删除归档记录'), ('rebuild', '重建修改记录')], default='archive', max_length=16, verbose_name='归档记录类型')),
            ],
            options={
                'verbose_name': '服务器归档记录',
                'verbose_name_plural': '服务器归档记录',
                'ordering': ['-deleted_time'],
            },
        ),
    ]
