# Generated by Django 3.1.5 on 2021-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_squashed_0007_serverarchive_user_quota_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serverarchive',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
