# Generated by Django 3.2.4 on 2021-06-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vo', '0001_initial'),
        ('servers', '0001_squashed_0007_serverarchive_user_quota_tag_squashed_0006_auto_20210407_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='vo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vo_server_set', to='vo.virtualorganization', verbose_name='项目组'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='vo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vo_server_archive_set', to='vo.virtualorganization', verbose_name='项目组'),
        ),
    ]
