# Generated by Django 3.2.13 on 2022-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='network_id',
            field=models.CharField(default='', max_length=64, verbose_name='网络ID'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='network_id',
            field=models.CharField(default='', max_length=64, verbose_name='网络ID'),
        ),
    ]
