# Generated by Django 3.1.5 on 2021-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20210128_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
