# Generated by Django 3.2.5 on 2021-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20210629_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='default_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='默认登录密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='default_user',
            field=models.CharField(default='', max_length=64, verbose_name='默认登录用户名'),
        ),
        migrations.AddField(
            model_name='server',
            name='image_desc',
            field=models.CharField(default='', max_length=255, verbose_name='镜像系统描述'),
        ),
        migrations.AddField(
            model_name='server',
            name='image_id',
            field=models.CharField(default='', max_length=64, verbose_name='镜像系统ID'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='default_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='默认登录密码'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='default_user',
            field=models.CharField(default='', max_length=64, verbose_name='默认登录用户名'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='image_desc',
            field=models.CharField(default='', max_length=255, verbose_name='镜像系统描述'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='image_id',
            field=models.CharField(default='', max_length=64, verbose_name='镜像系统ID'),
        ),
    ]
