# Generated by Django 3.1.7 on 2021-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20210204_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverarchive',
            name='user_quota_tag',
        ),
    ]
