# Generated by Django 3.2.13 on 2022-07-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20220627_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='situation',
            field=models.CharField(choices=[('normal', '正常'), ('expired', '过期停机'), ('arrearage', '欠费停机')], default='normal', help_text='过期欠费等状态下云主机的停机管控情况', max_length=16, verbose_name='过期欠费管控情况'),
        ),
        migrations.AddField(
            model_name='server',
            name='situation_time',
            field=models.DateTimeField(blank=True, default=None, help_text='过期欠费管控开始时间', null=True, verbose_name='管控情况时间'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='situation',
            field=models.CharField(choices=[('normal', '正常'), ('expired', '过期停机'), ('arrearage', '欠费停机')], default='normal', help_text='过期欠费等状态下云主机的停机管控情况', max_length=16, verbose_name='过期欠费管控情况'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='situation_time',
            field=models.DateTimeField(blank=True, default=None, help_text='过期欠费管控开始时间', null=True, verbose_name='管控情况时间'),
        ),
    ]
