# Generated by Django 3.1.7 on 2021-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_serverarchive_user_quota_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间'),
        ),
    ]
