# Generated by Django 2.2.16 on 2020-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20200930_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='center_quota',
            field=models.SmallIntegerField(choices=[(1, '私有资源配额'), (2, '共享资源配额')], default=2, verbose_name='数据中心配额'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='center_quota',
            field=models.SmallIntegerField(choices=[(1, '私有资源配额'), (2, '共享资源配额')], default=2, verbose_name='数据中心配额'),
        ),
    ]
