# Generated by Django 3.2.13 on 2022-11-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceconfig_pay_app_service_id'),
        ('servers', '0004_auto_20220711_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='服务单元'),
        ),
    ]
