# Generated by Django 3.1.7 on 2021-04-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20210407_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ['vcpus'], 'verbose_name': '配置样式', 'verbose_name_plural': '配置样式'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-creation_time'], 'verbose_name': '虚拟服务器', 'verbose_name_plural': '虚拟服务器'},
        ),
        migrations.AlterModelOptions(
            name='serverarchive',
            options={'ordering': ['-deleted_time'], 'verbose_name': '服务器归档记录', 'verbose_name_plural': '服务器归档记录'},
        ),
    ]
