# Generated by Django 3.2.13 on 2023-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_flavor_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tag描述'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='disk',
            field=models.IntegerField(default=0, verbose_name='硬盘GB'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='flavor_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='服务端规格ID'),
        ),
    ]
