# Generated by Django 3.2.5 on 2021-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='instance_name',
            field=models.CharField(blank=True, default='', help_text='各接入服务中云主机的名称', max_length=255, verbose_name='云主机实例名称'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='instance_name',
            field=models.CharField(blank=True, default='', help_text='各接入服务中云主机的名称', max_length=255, verbose_name='云主机实例名称'),
        ),
    ]
