# Generated by Django 3.2.5 on 2021-12-15 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0006_auto_20211214_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='email_lasttime',
            field=models.DateTimeField(blank=True, default=None, help_text='记录上次发邮件的时间，邮件通知用户配额即将到期', null=True, verbose_name='上次发送邮件时间'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='archive_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
    ]
