# Generated by Django 2.2.16 on 2020-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20201113_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverarchive',
            name='user_quota_tag',
            field=models.SmallIntegerField(choices=[(1, '普通配额'), (2, '试用配额')], default=1, verbose_name='配额类型'),
        ),
    ]
