# Generated by Django 3.2.5 on 2021-12-28 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20211215_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='云主机资源使用量计量开始时间', verbose_name='计量开始时间'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='archive_type',
            field=models.CharField(choices=[('archive', '删除归档记录'), ('rebuild', '重建修改记录')], default='archive', max_length=16, verbose_name='归档记录类型'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='云主机资源使用量计量开始时间', verbose_name='计量开始时间'),
        ),
    ]
