# Generated by Django 3.2.5 on 2022-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20211228_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='pay_type',
            field=models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='pay_type',
            field=models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='server_id',
            field=models.CharField(blank=True, default='', help_text='归档服务器的ID', max_length=36, verbose_name='服务器ID'),
        ),
    ]
