# Generated by Django 3.2.13 on 2023-06-20 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20230522_0631'),
        ('vo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0008_alter_server_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='云硬盘名称')),
                ('instance_id', models.CharField(help_text='各接入服务单元中云硬盘的ID', max_length=128, verbose_name='云硬盘实例ID')),
                ('instance_name', models.CharField(blank=True, default='', help_text='各接入服务单元中云硬盘的名称', max_length=255, verbose_name='云硬盘实例名称')),
                ('size', models.IntegerField(default=0, verbose_name='容量大小GiB')),
                ('azone_id', models.CharField(blank=True, default='', max_length=36, verbose_name='可用区Id')),
                ('azone_name', models.CharField(blank=True, default='', max_length=36, verbose_name='可用区名称')),
                ('quota_type', models.CharField(choices=[('private', '私有资源配额'), ('shared', '共享资源配额')], default='private', max_length=16, verbose_name='服务单元配额')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('task_status', models.CharField(choices=[('ok', '创建成功'), ('creating', '正在创建中'), ('failed', '创建失败')], default='ok', max_length=16, verbose_name='创建状态')),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='云硬盘资源使用量计量开始时间', verbose_name='计量开始时间')),
                ('pay_type', models.CharField(choices=[('prepaid', '包年包月'), ('postpaid', '按量计费'), ('quota', '资源配额券')], default='postpaid', max_length=16, verbose_name='计费方式')),
                ('classification', models.CharField(choices=[('personal', '个人的'), ('vo', 'VO组的')], default='personal', help_text='标识云硬盘属于申请者个人的，还是vo组的', max_length=16, verbose_name='云硬盘归属类型')),
                ('lock', models.CharField(choices=[('free', '无锁'), ('lock-delete', '锁定删除'), ('lock-operation', '锁定所有操作，只允许读')], default='free', help_text='加锁锁定云硬盘，防止误操作', max_length=16, verbose_name='锁')),
                ('email_lasttime', models.DateTimeField(blank=True, default=None, help_text='记录上次发邮件的时间，邮件通知用户云硬盘即将到期', null=True, verbose_name='上次发送邮件时间')),
                ('mountpoint', models.CharField(blank=True, default='', help_text='例如 "/dev/vdc"', max_length=64, verbose_name='挂载点/设备名')),
                ('attached_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='最后一次挂载时间')),
                ('detached_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='最后一次卸载时间')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounted_disk_set', to='servers.server', verbose_name='挂载于云主机')),
                ('service', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='服务单元')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('vo', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='项目组')),
                ('deleted', models.BooleanField(default=False, help_text='选中表示已删除', verbose_name='删除状态')),
                ('deleted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('deleted_user', models.CharField(default='', max_length=128, verbose_name='删除人')),
            ],
            options={
                'verbose_name': '云硬盘',
                'verbose_name_plural': '云硬盘',
                'db_table': 'servers_disk',
                'ordering': ['-creation_time'],
            },
        ),
    ]
