# Generated by Django 3.2.5 on 2022-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_auto_20220216_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='azone_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='可用区'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='azone_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='可用区'),
        ),
    ]
