# Generated by Django 3.2.13 on 2023-07-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_disk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceActionLog',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(editable=False, verbose_name='操作时间')),
                ('user_id', models.CharField(max_length=36, verbose_name='操作者id')),
                ('username', models.CharField(max_length=150, verbose_name='操作者')),
                ('action_flag', models.CharField(choices=[('add', '添加'), ('change', '修改'), ('delete', '删除')], max_length=16, verbose_name='操作类型')),
                ('resource_type', models.CharField(choices=[('server', '云主机'), ('disk', '云硬盘'), ('bucket', '存储桶')], max_length=16, verbose_name='资源类型')),
                ('resource_id', models.TextField(blank=True, null=True, verbose_name='资源id')),
                ('resource_repr', models.CharField(max_length=200, verbose_name='资源描述')),
                ('resource_message', models.JSONField(blank=True, verbose_name='资源信息')),
                ('owner_id', models.CharField(max_length=32, verbose_name='资源拥有者id')),
                ('owner_name', models.CharField(max_length=128, verbose_name='资源拥有者')),
                ('owner_type', models.CharField(choices=[('user', '用户'), ('vo', 'VO组')], max_length=16, verbose_name='资源拥有者类型')),
            ],
            options={
                'verbose_name': '资源操作日志',
                'verbose_name_plural': '资源操作日志',
                'db_table': 'resource_action_log',
                'ordering': ['-action_time'],
            },
        ),
    ]
