# Generated by Django 3.2.5 on 2022-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20220222_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='disk_size',
            field=models.IntegerField(default=0, verbose_name='系统盘GB'),
        ),
        migrations.AddField(
            model_name='serverarchive',
            name='disk_size',
            field=models.IntegerField(default=0, verbose_name='系统盘GB'),
        ),
    ]
