# Generated by Django 3.2.5 on 2022-04-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20220225_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='user_quota',
        ),
        migrations.RemoveField(
            model_name='serverarchive',
            name='user_quota',
        ),
    ]
