# Generated by Django 4.2.9 on 2024-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0002_vttask_balance_amount_vttask_coupon_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vtreport",
            name="size",
            field=models.IntegerField(default=0, verbose_name="文件大小"),
        ),
        migrations.AddField(
            model_name="vttask",
            name="errmsg",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="任务失败原因"
            ),
        ),
        migrations.AlterField(
            model_name="vttask",
            name="running_status",
            field=models.CharField(
                choices=[
                    ("spider", "爬虫"),
                    ("ajaxspider", "Ajax爬虫"),
                    ("active", "主动扫描"),
                    ("passive", "被动扫描"),
                    ("done", "运行结束"),
                    ("failed", "运行失败"),
                ],
                max_length=16,
                null=True,
                verbose_name="内部扫描状态",
            ),
        ),
    ]
