# Generated by Django 4.2.9 on 2024-03-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_remove_vttask_pay_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtscanservice',
            name='host_scan_price',
        ),
        migrations.RemoveField(
            model_name='vtscanservice',
            name='web_scan_price',
        ),
        migrations.RemoveField(
            model_name='vttask',
            name='payment_history_id',
        ),
    ]
