# Generated by Django 4.2.9 on 2024-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_delete_applyorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdatacenter',
            name='map_display',
            field=models.JSONField(blank=True, default=dict, verbose_name='地图显示配置信息'),
        ),
    ]
