# Generated by Django 4.2.9 on 2024-03-04 01:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vttask",
            name="balance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="余额支付金额",
            ),
        ),
        migrations.AddField(
            model_name="vttask",
            name="coupon_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="券支付金额",
            ),
        ),
        migrations.AddField(
            model_name="vttask",
            name="pay_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="实际交易金额",
                max_digits=10,
                verbose_name="实付金额",
            ),
        ),
    ]
