# Generated by Django 3.2.5 on 2021-07-07 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_auto_20210625_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaActivity',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配额活动名称')),
                ('name_en', models.CharField(max_length=255, verbose_name='配额活动英文名称')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='活动创建时间')),
                ('count', models.IntegerField(default=1, verbose_name='总数量')),
                ('got_count', models.IntegerField(default=0, verbose_name='已领取数量')),
                ('times_per_user', models.IntegerField(default=1, help_text='每个用户可领取次数', verbose_name='每人可领取次数')),
                ('status', models.CharField(choices=[('active', '活动中'), ('closed', '活动关闭')], default='active', max_length=16, verbose_name='活动状态')),
                ('deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('tag', models.CharField(choices=[('base', '普通配额'), ('probation', '试用配额')], default='probation', max_length=32, verbose_name='配额类型')),
                ('cpus', models.IntegerField(default=1, verbose_name='虚拟cpu数量')),
                ('private_ip', models.IntegerField(default=0, verbose_name='私网IP数')),
                ('public_ip', models.IntegerField(default=0, verbose_name='公网IP数')),
                ('ram', models.IntegerField(default=1024, verbose_name='内存大小(MB)')),
                ('disk_size', models.IntegerField(default=0, verbose_name='总硬盘大小(GB)')),
                ('expiration_time', models.DateTimeField(help_text='过期后不能再用于创建资源', verbose_name='配额过期时间')),
                ('duration_days', models.IntegerField(blank=True, default=365, help_text='使用此配额创建的资源的有效使用时长', verbose_name='资源使用时长')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='服务provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'ordering': ('-creation_time',),
                'verbose_name': '配额活动',
                'verbose_name_plural': '配额活动',
                'db_table': 'quota_activity',
            },
        ),
        migrations.CreateModel(
            name='QuotaActivityGotRecord',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('got_count', models.IntegerField(default=0, verbose_name='领取次数')),
                ('quota_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activity.quotaactivity', verbose_name='配额活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ('-got_time',),
                'verbose_name': '配额活动领取记录',
                'verbose_name_plural': '配额活动领取记录',
                'db_table': 'quota_activity_got_record',
            },
        ),
        migrations.AddConstraint(
            model_name='quotaactivitygotrecord',
            constraint=models.UniqueConstraint(fields=('user', 'quota_activity'), name='unique_together_quota_activity_user'),
        ),
    ]
