# Generated by Django 3.2.5 on 2022-04-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotaActivity',
        ),
        migrations.DeleteModel(
            name='QuotaActivityGotRecord',
        ),
    ]
