# Generated by Django 3.2.5 on 2022-05-07 01:58

import activity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0008_auto_20220422_0757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vo', '0001_initial'),
        ('activity', '0002_auto_20220422_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCouponActivity',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expiration_time', models.DateTimeField(verbose_name='过期时间')),
                ('coupon_type', models.CharField(choices=[('universal', '通用'), ('special', '专用')], default='universal', max_length=16, verbose_name='券类型')),
                ('_applicable_resource', activity.models.ApplicableResourceField(blank=True, db_column='applicable_resource', default=list, help_text='空表示通用', verbose_name='适用资源')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('grant_total', models.IntegerField(default=0, verbose_name='发放总数量')),
                ('granted_count', models.IntegerField(default=0, verbose_name='已发放数量')),
                ('grant_status', models.CharField(choices=[('wait', '待发放'), ('grant', '发放中'), ('completed', '发放完毕')], default='wait', max_length=16, verbose_name='发放状态')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='描述信息')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='适用服务')),
            ],
            options={
                'verbose_name': '代金券活动',
                'verbose_name_plural': '代金券活动',
                'db_table': 'cash_coupon_activity',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='CashCoupon',
            fields=[
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面额')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expiration_time', models.DateTimeField(verbose_name='过期时间')),
                ('coupon_type', models.CharField(choices=[('universal', '通用'), ('special', '专用')], default='universal', max_length=16, verbose_name='券类型')),
                ('_applicable_resource', activity.models.ApplicableResourceField(blank=True, db_column='applicable_resource', default=list, help_text='空表示通用', verbose_name='适用资源')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='编码')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('status', models.CharField(choices=[('wait', '未领取'), ('available', '有效'), ('cancelled', '作废'), ('deleted', '删除')], default='wait', max_length=16, verbose_name='状态')),
                ('granted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='领取/发放时间')),
                ('owner_type', models.CharField(blank=True, choices=[('user', '用户'), ('vo', 'VO组'), ('', '未知')], default='', max_length=16, verbose_name='所属类型')),
                ('_coupon_code', models.CharField(db_column='coupon_code', max_length=64, verbose_name='券密码')),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activity.cashcouponactivity', verbose_name='活动')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.serviceconfig', verbose_name='适用服务')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='VO组')),
            ],
            options={
                'verbose_name': '代金券',
                'verbose_name_plural': '代金券',
                'db_table': 'cash_coupon',
                'ordering': ['-creation_time'],
            },
        ),
    ]
