# Generated by Django 3.2.13 on 2022-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashcoupon',
            name='_applicable_resource',
        ),
        migrations.RemoveField(
            model_name='cashcoupon',
            name='coupon_type',
        ),
        migrations.RemoveField(
            model_name='cashcouponactivity',
            name='_applicable_resource',
        ),
        migrations.RemoveField(
            model_name='cashcouponactivity',
            name='coupon_type',
        ),
        migrations.AddField(
            model_name='cashcouponactivity',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='创建人'),
        ),
    ]
