# Generated by Django 4.2.9 on 2024-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_resource_instance_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_action',
            field=models.CharField(choices=[('none', '无'), ('delivering', '正在交付订单资源')], default='none', help_text='用于记录订单当前的操作动作，比如是否正在交付资源中，防止并发时订单业务冲突', max_length=16, verbose_name='资源交付动作'),
        ),
    ]
