# Generated by Django 4.2.9 on 2024-06-21 01:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_period_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='vm_base',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='每小时云主机基础维护费价格', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每小时云主机基础维护费'),
        ),
    ]
