# Generated by Django 4.2.4 on 2023-08-29 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vo', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='userpointaccount',
        #     name='user',
        #     field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddIndex(
            model_name='transactionbill',
            index=models.Index(fields=['owner_id'], name='idx_owner_id'),
        ),
        migrations.AddIndex(
            model_name='transactionbill',
            index=models.Index(fields=['trade_id'], name='idx_trade_id'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['trade_id'], name='idx_refund_trade_id'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['out_refund_id'], name='idx_refund_out_refund_id'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['owner_id'], name='idx_recharge_owner_id'),
        ),
        migrations.AddField(
            model_name='payorgnazition',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payer_id'], name='idx_payer_id'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
        migrations.AddField(
            model_name='payappservice',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bill.payapp', verbose_name='应用APP'),
        ),
        migrations.AddField(
            model_name='payappservice',
            name='orgnazition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bill.payorgnazition', verbose_name='机构|组织'),
        ),
        migrations.AddField(
            model_name='payappservice',
            name='users',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='pay_app_service_users', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
        migrations.AddField(
            model_name='cashcouponpaymenthistory',
            name='cash_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.cashcoupon', verbose_name='资源券'),
        ),
        migrations.AddField(
            model_name='cashcouponpaymenthistory',
            name='payment_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.paymenthistory', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='cashcouponactivity',
            name='app_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.payappservice', verbose_name='适用服务'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.cashcouponactivity', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='app_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bill.payappservice', verbose_name='适用服务'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cashcoupon',
            name='vo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vo.virtualorganization', verbose_name='VO组'),
        ),
    ]
