# Generated by Django 4.2.9 on 2024-01-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_cashcoupon_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayOrgnazition',
        ),
    ]
