# Generated by Django 4.2.9 on 2024-04-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCpuUsage',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField(verbose_name='统计时间')),
                ('value', models.FloatField(help_text='负数标识数据无效（查询失败的占位记录，便于后补）', verbose_name='CPU使用率')),
                ('unit', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_screenvis.metricmonitorunit', verbose_name='指标单元ID')),
            ],
            options={
                'verbose_name': '主机指标单元总CPU使用率时序数据',
                'verbose_name_plural': '主机指标单元总CPU使用率时序数据',
                'db_table': 'screenvis_hostcpuusage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_screen_cpuusage_ts')],
            },
        ),
    ]
