# Generated by Django 4.2.9 on 2024-04-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0003_apiallowip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='服务名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='服务英文名称')),
                ('endpoint_url', models.CharField(help_text='http(s)://{hostname}:{port}/', max_length=255, verbose_name='服务地址url')),
                ('username', models.CharField(help_text='用于此服务认证的用户名', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('status', models.CharField(choices=[('enable', '服务中'), ('disable', '暂停服务'), ('deleted', '删除')], default='enable', max_length=32, verbose_name='服务状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_weight', models.IntegerField(default=0, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('data_center', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_screenvis.datacenter', verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '对象存储服务单元',
                'verbose_name_plural': '对象存储服务单元',
                'db_table': 'screenvis_objectservice',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='ServerService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='服务名称')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='服务英文名称')),
                ('endpoint_url', models.CharField(help_text='http(s)://{hostname}:{port}/', max_length=255, verbose_name='服务地址url')),
                ('username', models.CharField(help_text='用于此服务认证的用户名', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('status', models.CharField(choices=[('enable', '服务中'), ('disable', '暂停服务'), ('deleted', '删除')], default='enable', max_length=32, verbose_name='服务状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_weight', models.IntegerField(default=0, help_text='值越小排序越靠前', verbose_name='排序值')),
                ('data_center', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_screenvis.datacenter', verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '云主机服务单元',
                'verbose_name_plural': '云主机服务单元',
                'db_table': 'screenvis_serverservice',
                'ordering': ['sort_weight'],
            },
        ),
        migrations.CreateModel(
            name='VPNTimedStats',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField(verbose_name='统计时间')),
                ('vpn_online_count', models.IntegerField(blank=True, default=0, verbose_name='VPN账户在线数')),
                ('vpn_active_count', models.IntegerField(blank=True, default=0, verbose_name='VPN有效数')),
                ('vpn_count', models.IntegerField(blank=True, default=0, verbose_name='VPN总数')),
                ('service', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_screenvis.serverservice', verbose_name='服务单元')),
            ],
            options={
                'verbose_name': 'VPN时序统计数据',
                'verbose_name_plural': 'VPN时序统计数据',
                'db_table': 'screenvis_vpn_timedstats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_screen_vpn_tmstats_ts')],
            },
        ),
        migrations.CreateModel(
            name='ServerServiceTimedStats',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField(verbose_name='统计时间')),
                ('server_count', models.IntegerField(blank=True, default=0, verbose_name='云主机数')),
                ('disk_count', models.IntegerField(blank=True, default=0, verbose_name='云硬盘数')),
                ('ip_count', models.IntegerField(blank=True, default=0, verbose_name='IP总数')),
                ('ip_used_count', models.IntegerField(blank=True, default=0, verbose_name='已用IP数')),
                ('mem_size', models.IntegerField(blank=True, default=0, verbose_name='内存总数(GiB)')),
                ('mem_used_size', models.IntegerField(blank=True, default=0, verbose_name='已用内存总数(GiB)')),
                ('cpu_count', models.IntegerField(blank=True, default=0, verbose_name='CPU总数')),
                ('cpu_used_count', models.IntegerField(blank=True, default=0, verbose_name='已用CPU总数')),
                ('service', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_screenvis.serverservice', verbose_name='服务单元')),
            ],
            options={
                'verbose_name': '云主机服务单元时序统计数据',
                'verbose_name_plural': '云主机服务单元时序统计数据',
                'db_table': 'screenvis_server_timedstats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_screen_server_tmstats_ts')],
            },
        ),
        migrations.CreateModel(
            name='ObjectServiceTimedStats',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField(verbose_name='统计时间')),
                ('bucket_count', models.IntegerField(blank=True, default=0, verbose_name='存储桶总数')),
                ('bucket_storage', models.BigIntegerField(blank=True, default=0, verbose_name='存储桶总数据量(GiB)')),
                ('storage_used', models.BigIntegerField(blank=True, default=0, verbose_name='已用容量(GiB)')),
                ('storage_capacity', models.BigIntegerField(blank=True, default=0, verbose_name='总容量(GiB)')),
                ('service', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_screenvis.objectservice', verbose_name='服务单元')),
            ],
            options={
                'verbose_name': '对象存储服务单元时序统计数据',
                'verbose_name_plural': '对象存储服务单元时序统计数据',
                'db_table': 'screenvis_object_timedstats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_screen_obj_tmstats_ts')],
            },
        ),
    ]
