# Generated by Django 4.2.9 on 2024-05-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0006_objectservicelog_create_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiAllowIP',
        ),
    ]
