# Generated by Django 4.2.9 on 2024-05-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0007_delete_apiallowip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostNetflow',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField(verbose_name='统计时间')),
                ('flow_in', models.FloatField(help_text='负数标识数据无效（查询失败的占位记录，便于后补）', verbose_name='进流量(B/s)')),
                ('flow_out', models.FloatField(help_text='负数标识数据无效（查询失败的占位记录，便于后补）', verbose_name='出流量(B/s)')),
                ('unit', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_screenvis.metricmonitorunit', verbose_name='指标单元ID')),
            ],
            options={
                'verbose_name': '主机指标单元网络流量',
                'verbose_name_plural': '主机指标单元网络流量',
                'db_table': 'screenvis_hostnetflow',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_screen_netflow_ts')],
            },
        ),
    ]
