# Generated by Django 4.2.9 on 2024-06-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0008_hostnetflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMonitorTask',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.CharField(default='', max_length=2048, verbose_name='要监控的网址')),
                ('url_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='网址hash值')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_tamper_resistant', models.BooleanField(blank=True, default=False, verbose_name='防篡改')),
                ('data_center', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_screenvis.datacenter', verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '网站监控任务',
                'verbose_name_plural': '网站监控任务',
                'db_table': 'screenvis_website_task',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='websitemonitortask',
            constraint=models.UniqueConstraint(fields=('url_hash',), name='uniq_screenvis_webtask_url_hash'),
        ),
    ]
