# Generated by Django 4.2.9 on 2024-06-24 03:02

from django.db import migrations, connection

from apps.app_screenvis.configs_manager import screen_configs


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]


def run_copy_metric_query_url(apps, schema_editor):
    with connection.cursor() as cursor:
        try:
            cursor.execute('SELECT `metric_endpoint_url` FROM `screenvis_data_center` LIMIT 1;')
            data = dictfetchall(cursor)
            if data:
                metric_endpoint_url = data[0]['metric_endpoint_url']
                screen_configs.add_or_update(
                    screen_configs.ConfigName.METRIC_QUERY_ENDPOINT_URL.value, value=metric_endpoint_url)
                print(f'[Ok] 更新指标数据查询地址配置({metric_endpoint_url}) 从 数据中心表')
        except Exception as exc:
            pass


def do_nothing(apps, schema_editor):
    print('do nothing')


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0009_websitemonitortask_and_more'),
    ]

    operations = [
        migrations.RunPython(run_copy_metric_query_url, reverse_code=do_nothing),
        migrations.RemoveField(
            model_name='logmonitorunit',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='metricmonitorunit',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='objectservice',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='serverservice',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='websitemonitortask',
            name='data_center',
        ),
    ]
