# Generated by Django 4.2.9 on 2024-06-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_screenvis', '0010_remove_logmonitorunit_data_center_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCenter',
        ),
        migrations.DeleteModel(
            name='HostCpuUsage',
        ),
    ]
