# Generated by Django 4.2.5 on 2023-10-20 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_contacts_datacenter_province_datacenter_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorBox',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_link_id', models.TextField(blank=True, default='', verbose_name='链路id')),
                ('number', models.CharField(default='', help_text='自定义编号', max_length=24, verbose_name='接头盒编号')),
                ('place', models.CharField(blank=True, default='', max_length=128, verbose_name='位置')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='经纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '光缆接头盒',
                'verbose_name_plural': '光缆接头盒',
                'db_table': 'link_connector_box',
            },
        ),
        migrations.CreateModel(
            name='DistributionFrame',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=24, verbose_name='设备号')),
                ('model_type', models.CharField(blank=True, default='', max_length=36, verbose_name='设备型号')),
                ('size', models.CharField(blank=True, default='', max_length=36, verbose_name='行列数')),
                ('place', models.CharField(blank=True, default='', max_length=128, verbose_name='位置')),
                ('institution_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='机构ID')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配线架',
                'verbose_name_plural': '配线架',
                'db_table': 'link_distribution_frame',
            },
        ),
        migrations.CreateModel(
            name='ElementLink',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=24, verbose_name='链路编号')),
                ('serials', models.TextField(default='', help_text='逗号分隔', verbose_name='网元序列')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('link_status', models.CharField(choices=[('using', '使用'), ('idle', '闲置'), ('backup', '备用'), ('deleted', '删除')], default='idle', max_length=16, verbose_name='链路状态')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='机构ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '链路',
                'verbose_name_plural': '链路',
                'db_table': 'link_element_link',
            },
        ),
        migrations.CreateModel(
            name='FiberCable',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=24, verbose_name='光缆编号')),
                ('fiber_count', models.IntegerField(default=0, verbose_name='总纤芯数量')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='km', max_digits=10, null=True, verbose_name='长度')),
                ('endpoint_1', models.CharField(blank=True, default='', max_length=255, verbose_name='端点1')),
                ('endpoint_2', models.CharField(blank=True, default='', max_length=255, verbose_name='端点2')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('fiber_ids', models.TextField(blank=True, default='', help_text='逗号分隔', verbose_name='光纤ID列表')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '光缆',
                'verbose_name_plural': '光缆',
                'db_table': 'link_fiber_cable',
            },
        ),
        migrations.CreateModel(
            name='LeaseLine',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_link_id', models.TextField(blank=True, default='', verbose_name='链路id')),
                ('private_line_number', models.CharField(blank=True, default='', max_length=64, verbose_name='专线号')),
                ('lease_line_code', models.CharField(blank=True, default='', max_length=64, verbose_name='电路代号')),
                ('line_username', models.CharField(blank=True, default='', max_length=36, verbose_name='专线用户')),
                ('endpoint_a', models.CharField(blank=True, default='', max_length=255, verbose_name='A端')),
                ('endpoint_z', models.CharField(blank=True, default='', max_length=255, verbose_name='Z端')),
                ('line_type', models.CharField(blank=True, default='', max_length=36, verbose_name='线路类型')),
                ('cable_type', models.CharField(blank=True, default='', max_length=36, verbose_name='电路类型')),
                ('bandwidth', models.IntegerField(blank=True, default=None, help_text='Mbs', null=True, verbose_name='带宽')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='km', max_digits=10, null=True, verbose_name='长度')),
                ('provider', models.CharField(blank=True, default='', max_length=36, verbose_name='运营商')),
                ('enable_date', models.DateField(blank=True, default=None, null=True, verbose_name='开通日期')),
                ('is_whithdrawal', models.BooleanField(default=False, help_text='0:在网 1:撤线', verbose_name='租线状态')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='元', max_digits=10, null=True, verbose_name='月租费')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租用线路',
                'verbose_name_plural': '租用线路',
                'db_table': 'link_lease_line',
                'ordering': ('-update_time',),
            },
        ),
        migrations.CreateModel(
            name='OpticalFiber',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_link_id', models.TextField(blank=True, default='', verbose_name='链路id')),
                ('fiber_cable_id', models.CharField(db_index=True, default='', max_length=36, verbose_name='光缆ID')),
                ('sequence', models.IntegerField(default=0, verbose_name='纤序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '光纤',
                'verbose_name_plural': '光纤',
                'db_table': 'link_optical_fiber',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_link_id', models.TextField(blank=True, default='', verbose_name='链路id')),
                ('number', models.CharField(default='', help_text='自定义编号', max_length=24, verbose_name='端口编号')),
                ('model_type', models.CharField(blank=True, default='', max_length=36, verbose_name='型号')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='详情')),
                ('distribution_frame_id', models.CharField(db_index=True, default='', max_length=36, verbose_name='配线架id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '端口',
                'verbose_name_plural': '端口',
                'db_table': 'link_port',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=24, verbose_name='业务编号')),
                ('user', models.CharField(blank=True, default='', max_length=36, verbose_name='用户（单位）')),
                ('endpoint_a', models.CharField(blank=True, default='', max_length=255, verbose_name='A端')),
                ('endpoint_z', models.CharField(blank=True, default='', max_length=255, verbose_name='Z端')),
                ('bandwidth', models.IntegerField(blank=True, default=None, help_text='Mbs', null=True, verbose_name='带宽')),
                ('task_description', models.CharField(blank=True, default='', max_length=255, verbose_name='业务描述')),
                ('line_type', models.CharField(blank=True, default='', max_length=36, verbose_name='线路类型')),
                ('task_person', models.CharField(blank=True, default='', max_length=36, verbose_name='商务对接')),
                ('build_person', models.CharField(blank=True, default='', max_length=36, verbose_name='线路搭建')),
                ('task_status', models.CharField(choices=[('normal', '正常'), ('deleted', '删除')], default='normal', max_length=16, verbose_name='业务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务',
                'verbose_name_plural': '业务',
                'db_table': 'link_task',
            },
        ),
        migrations.CreateModel(
            name='LinkUserRole',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='用户拥有科技网链路管理功能的管理员权限', verbose_name='科技网IP管理员')),
                ('is_readonly', models.BooleanField(default=False, help_text='用户拥有科技网链路管理功能的全局只读权限', verbose_name='IP管理全局只读权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_linkuserrole', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '链路管理用户角色和权限',
                'verbose_name_plural': '链路管理用户角色和权限',
                'db_table': 'link_user_role',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='LinkOrg',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='机构名')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='经纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datacenter_linkorg', to='service.datacenter', verbose_name='分配机构')),
            ],
            options={
                'verbose_name': '机构二级',
                'verbose_name_plural': '机构二级',
                'db_table': 'link_org',
                'ordering': ('-create_time',),
            },
        ),
    ]
