# Generated by Django 4.2.5 on 2023-10-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_contacts_datacenter_province_datacenter_contacts'),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistriFramePort',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', help_text='自定义编号', max_length=64, verbose_name='端口编号')),
                ('row', models.IntegerField(default=None, verbose_name='行号')),
                ('col', models.IntegerField(default=None, verbose_name='列号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配线架端口',
                'verbose_name_plural': '配线架端口',
                'db_table': 'link_distriframe_port',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('optical-fiber', '光纤'), ('lease-line', '租用线路'), ('distributionframe-port', '配线架端口'), ('connector-box', '光缆接头盒')], max_length=32, verbose_name='网元对象类型')),
                ('object_id', models.CharField(db_index=True, max_length=36, verbose_name='网元对象id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网元汇总表',
                'verbose_name_plural': '网元汇总表',
                'db_table': 'link_element',
            },
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.RemoveField(
            model_name='connectorbox',
            name='element_link_id',
        ),
        migrations.RemoveField(
            model_name='distributionframe',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='distributionframe',
            name='institution_id',
        ),
        migrations.RemoveField(
            model_name='distributionframe',
            name='size',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='serials',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='fibercable',
            name='fiber_ids',
        ),
        migrations.RemoveField(
            model_name='leaseline',
            name='element_link_id',
        ),
        migrations.RemoveField(
            model_name='linkorg',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='opticalfiber',
            name='element_link_id',
        ),
        migrations.RemoveField(
            model_name='opticalfiber',
            name='fiber_cable_id',
        ),
        migrations.AddField(
            model_name='distributionframe',
            name='col_count',
            field=models.IntegerField(default=None, verbose_name='列数'),
        ),
        migrations.AddField(
            model_name='distributionframe',
            name='link_org',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkorg_distriframe', to='link.linkorg', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='distributionframe',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='设备号'),
        ),
        migrations.AddField(
            model_name='distributionframe',
            name='row_count',
            field=models.IntegerField(default=None, verbose_name='行数'),
        ),
        migrations.AddField(
            model_name='elementlink',
            name='element_ids',
            field=models.TextField(blank=True, default='', help_text='逗号分隔', verbose_name='网元序列'),
        ),
        migrations.AddField(
            model_name='elementlink',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_elementLink', to='link.task', verbose_name='业务'),
        ),
        migrations.AddField(
            model_name='linkorg',
            name='data_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datacenter_linkorg', to='service.datacenter', verbose_name='主机构'),
        ),
        migrations.AddField(
            model_name='opticalfiber',
            name='fiber_cable',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibercable_opticalfiber', to='link.fibercable', verbose_name='光缆'),
        ),
        migrations.AlterField(
            model_name='connectorbox',
            name='number',
            field=models.CharField(default='', help_text='自定义编号', max_length=64, verbose_name='接头盒编号'),
        ),
        migrations.AlterField(
            model_name='elementlink',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='链路编号'),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='fiber_count',
            field=models.IntegerField(verbose_name='总纤芯数量'),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='光缆编号'),
        ),
        migrations.AlterField(
            model_name='leaseline',
            name='is_whithdrawal',
            field=models.BooleanField(default=False, help_text='0:在网 1:撤线', verbose_name='是否撤线'),
        ),
        migrations.AlterField(
            model_name='linkorg',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='二级机构名'),
        ),
        migrations.AlterField(
            model_name='linkuserrole',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='用户拥有科技网链路管理功能的管理员权限', verbose_name='链路管理员权限'),
        ),
        migrations.AlterField(
            model_name='linkuserrole',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='用户拥有科技网链路管理功能的全局只读权限', verbose_name='链路只读权限'),
        ),
        migrations.AlterField(
            model_name='opticalfiber',
            name='sequence',
            field=models.IntegerField(verbose_name='纤序'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='业务编号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='用户（单位）'),
        ),
        migrations.AddField(
            model_name='distriframeport',
            name='distribution_frame',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distriframe_distriframeport', to='link.distributionframe', verbose_name='配线架'),
        ),
        migrations.AddField(
            model_name='distriframeport',
            name='element',
            field=models.OneToOneField(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_%(class)s', to='link.element', verbose_name='网元记录'),
        ),
        migrations.AddField(
            model_name='connectorbox',
            name='element',
            field=models.OneToOneField(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_%(class)s', to='link.element', verbose_name='网元记录'),
        ),
        migrations.AddField(
            model_name='leaseline',
            name='element',
            field=models.OneToOneField(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_%(class)s', to='link.element', verbose_name='网元记录'),
        ),
        migrations.AddField(
            model_name='opticalfiber',
            name='element',
            field=models.OneToOneField(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_%(class)s', to='link.element', verbose_name='网元记录'),
        ),
    ]
