# Generated by Django 4.2.5 on 2023-11-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_distriframeport_element_delete_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=64, verbose_name='编号')),
                ('user', models.CharField(blank=True, default='', max_length=128, verbose_name='用户（单位）')),
                ('endpoint_a', models.CharField(blank=True, default='', max_length=255, verbose_name='A端')),
                ('endpoint_z', models.CharField(blank=True, default='', max_length=255, verbose_name='Z端')),
                ('bandwidth', models.IntegerField(blank=True, default=None, help_text='Mbps', null=True, verbose_name='带宽')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='用途描述')),
                ('line_type', models.CharField(blank=True, default='', max_length=36, verbose_name='线路类型')),
                ('business_person', models.CharField(blank=True, default='', max_length=36, verbose_name='商务对接')),
                ('build_person', models.CharField(blank=True, default='', max_length=36, verbose_name='线路搭建')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('link_status', models.CharField(choices=[('using', '使用'), ('backup', '备用'), ('idle', '闲置')], default='idle', max_length=16, verbose_name='链路状态')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('enable_date', models.DateField(blank=True, default=None, null=True, verbose_name='开通日期')),
            ],
            options={
                'verbose_name': '链路',
                'verbose_name_plural': '链路',
                'db_table': 'link_link',
                'ordering': ('-update_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='distriframeport',
            options={'ordering': ('distribution_frame_id', 'row', 'col'), 'verbose_name': '配线架端口', 'verbose_name_plural': '配线架端口'},
        ),
        migrations.AlterModelOptions(
            name='elementlink',
            options={'ordering': ('link_id', 'index', 'sub_index'), 'verbose_name': '链路网元对应表', 'verbose_name_plural': '链路网元对应表'},
        ),
        migrations.AlterModelOptions(
            name='opticalfiber',
            options={'ordering': ('fiber_cable_id', 'sequence'), 'verbose_name': '光纤', 'verbose_name_plural': '光纤'},
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='element_ids',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='link_status',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='number',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='task',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='update_time',
        ),
        migrations.AddField(
            model_name='elementlink',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='element_link', to='link.element', verbose_name='网元'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementlink',
            name='index',
            field=models.IntegerField(default=1, verbose_name='链路位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementlink',
            name='sub_index',
            field=models.IntegerField(default=1, verbose_name='同位编号'),
        ),
        migrations.AlterField(
            model_name='element',
            name='object_type',
            field=models.CharField(choices=[('fiber', '光纤'), ('lease', '租用线路'), ('port', '配线架端口'), ('box', '光缆接头盒')], max_length=32, verbose_name='网元对象类型'),
        ),
        migrations.AlterField(
            model_name='leaseline',
            name='bandwidth',
            field=models.IntegerField(blank=True, default=None, help_text='Mbps', null=True, verbose_name='带宽'),
        ),
        migrations.AlterModelTable(
            name='elementlink',
            table='link_elementlink',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='link',
            name='elements',
            field=models.ManyToManyField(related_name='links', through='link.ElementLink', to='link.element', verbose_name='网元'),
        ),
        migrations.AddField(
            model_name='elementlink',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='element_link', to='link.link', verbose_name='业务链路'),
            preserve_default=False,
        ),
    ]
