# Generated by Django 4.2.9 on 2024-01-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_remove_ipv4address_ip_range'),
        ('link', '0001_initial_squashed_003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionframe',
            name='link_org',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.orgvirtualobject', verbose_name='机构二级'),
        ),
        migrations.DeleteModel(
            name='LinkOrg',
        ),
    ]
