# Generated by Django 4.2.9 on 2024-01-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_distributionframe_link_org_delete_linkorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionframe',
            name='link_org',
        ),
        migrations.RemoveField(
            model_name='distriframeport',
            name='distribution_frame',
        ),
        migrations.RemoveField(
            model_name='distriframeport',
            name='element',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='element',
        ),
        migrations.RemoveField(
            model_name='elementlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='leaseline',
            name='element',
        ),
        migrations.RemoveField(
            model_name='link',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='linkuserrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='opticalfiber',
            name='element',
        ),
        migrations.RemoveField(
            model_name='opticalfiber',
            name='fiber_cable',
        ),
        migrations.DeleteModel(
            name='ConnectorBox',
        ),
        migrations.DeleteModel(
            name='DistributionFrame',
        ),
        migrations.DeleteModel(
            name='DistriFramePort',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='ElementLink',
        ),
        migrations.DeleteModel(
            name='FiberCable',
        ),
        migrations.DeleteModel(
            name='LeaseLine',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinkUserRole',
        ),
        migrations.DeleteModel(
            name='OpticalFiber',
        ),
    ]
