# Generated by Django 4.2.5 on 2023-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorWebsiteRecord',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='网站名称')),
                ('url_hash', models.CharField(default='', max_length=64, verbose_name='网址hash值')),
                ('creation', models.DateTimeField(verbose_name='创建时间')),
                ('modification', models.DateTimeField(verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_tamper_resistant', models.BooleanField(default=False, verbose_name='防篡改')),
                ('scheme', models.CharField(default='', help_text='https|tcp://', max_length=32, verbose_name='协议')),
                ('hostname', models.CharField(default='', help_text='hostname:8000', max_length=255, verbose_name='域名[:端口]')),
                ('uri', models.CharField(default='', help_text='/a/b?query=123#test', max_length=1024, verbose_name='URI')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('type', models.CharField(choices=[('deleted', '删除')], max_length=16, verbose_name='记录类型')),
            ],
            options={
                'verbose_name': '网站监控任务记录',
                'verbose_name_plural': '网站监控任务记录',
                'db_table': 'monitor_website_record',
                'ordering': ['-record_time'],
            },
        ),
        migrations.AddField(
            model_name='monitorwebsiteversion',
            name='pay_app_service_id',
            field=models.CharField(default='', help_text='此服务对应的APP服务（注册在余额结算中的APP服务）id，扣费时需要此id，用于指定哪个服务发生的扣费', max_length=36, verbose_name='余额结算APP子服务ID'),
        ),
    ]
