# Generated by Django 4.2.5 on 2023-10-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorwebsiterecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorwebsite',
            name='url',
            field=models.CharField(default='', help_text='http(s)|tcp://xxx.xxx', max_length=2048, verbose_name='要监控的网址'),
        ),
    ]
