# Generated by Django 4.2.8 on 2023-12-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_squashed_0010_remove_datacenter_endpoint_compute_and_more'),
        ('monitor', '0008_alter_logsitetimereqnum_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorwebsite',
            name='url',
        ),
        migrations.AddField(
            model_name='monitorwebsite',
            name='odc',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='关联数据中心后，数据中心管理员有权限访问此监控任务的数据，无监控任务的管理权限；数据中心与用户原则上只能关联其一', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.orgdatacenter', verbose_name='数据中心'),
        ),
    ]
