# Generated by Django 4.2.9 on 2024-01-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_monitorwebsite_url_monitorwebsite_odc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, default=0, verbose_name='状态码')),
                ('method', models.CharField(blank=True, default='', max_length=32, verbose_name='请求方法')),
                ('full_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='URI')),
                ('message', models.TextField(blank=True, default='', verbose_name='日志信息')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='请求用户')),
            ],
            options={
                'verbose_name': '错误日志',
                'verbose_name_plural': '错误日志',
                'db_table': 'error_log',
                'ordering': ['-creation'],
            },
        ),
    ]
