# Generated by Django 4.2.9 on 2024-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetectionpoint',
            name='sort_weight',
            field=models.IntegerField(default=0, help_text='值越小排序越靠前', verbose_name='排序值'),
        ),
    ]
