# Generated by Django 4.2.9 on 2024-04-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeDetails',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_type', models.PositiveSmallIntegerField(choices=[(1, '中国科技网'), (2, '北京联通'), (3, '北京电信')], default=None, verbose_name='探针')),
                ('version', models.IntegerField(blank=True, default=0, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '探针信息',
                'verbose_name_plural': '探针信息',
                'db_table': 'app_probe_details',
            },
        ),
        migrations.CreateModel(
            name='ProbeMonitorWebsite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(default='', max_length=64, verbose_name='网址hash值')),
                ('is_tamper_resistant', models.BooleanField(default=False, verbose_name='防篡改')),
                ('uri', models.CharField(default='', help_text='/a/b?query=123#test', max_length=1024, verbose_name='URI')),
                ('creation', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '探针任务',
                'verbose_name_plural': '探针任务',
                'db_table': 'app_probe_monitor_website',
                'ordering': ['-creation'],
            },
        ),
    ]
