# Generated by Django 4.2.9 on 2024-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_probe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probemonitorwebsite',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
