# Generated by Django 4.2.9 on 2024-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_probe', '0004_alter_probemonitorwebsite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='uri',
        ),
        migrations.AddField(
            model_name='probemonitorwebsite',
            name='url',
            field=models.CharField(default='', max_length=2048, verbose_name='要监控的网址'),
        ),
        migrations.AlterField(
            model_name='probemonitorwebsite',
            name='url_hash',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='网址hash值'),
        ),
    ]
