# Generated by Django 4.2.9 on 2024-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_probe', '0005_remove_probemonitorwebsite_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probedetails',
            name='probe_type',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='connect_time',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='resolve_time',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='status',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='tls_time',
        ),
        migrations.RemoveField(
            model_name='probemonitorwebsite',
            name='transfer_time',
        ),
        migrations.AddField(
            model_name='probedetails',
            name='probe_name',
            field=models.CharField(default=None, max_length=255, verbose_name='探针服务名称'),
        ),
    ]
