# Generated by Django 4.2.9 on 2024-06-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_totalreqnum_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetectionpoint',
            name='auth_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='探针服务认证密码'),
        ),
        migrations.AddField(
            model_name='websitedetectionpoint',
            name='auth_username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='探针服务认证用户'),
        ),
        migrations.AddField(
            model_name='websitedetectionpoint',
            name='endpoint_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='监控任务提交探针服务地址'),
        ),
        migrations.CreateModel(
            name='ProbeTaskSubmitLog',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', '添加'), ('update', '更新'), ('delete', '删除')], max_length=16, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('sucess', '成功'), ('failed', '失败')], max_length=16, verbose_name='状态')),
                ('task_url', models.CharField(max_length=2048, verbose_name='监控网址')),
                ('task_url_hash', models.CharField(max_length=64, verbose_name='网址hash值')),
                ('task_is_tamper', models.BooleanField(default=False, verbose_name='防篡改')),
                ('new_url', models.CharField(default='', max_length=2048, verbose_name='新的监控网址')),
                ('new_url_hash', models.CharField(default='', max_length=64, verbose_name='新的网址hash值')),
                ('new_is_tamper', models.BooleanField(default=False, verbose_name='新网址防篡改')),
                ('task_version', models.IntegerField(default=0, verbose_name='监控任务版本号')),
                ('desc', models.CharField(default='', max_length=2048, verbose_name='描述信息')),
                ('creation', models.DateTimeField(verbose_name='创建时间')),
                ('probe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.websitedetectionpoint', verbose_name='探测点')),
            ],
            options={
                'verbose_name': '网站探测点任务提交记录',
                'verbose_name_plural': '网站探测点任务提交记录',
                'db_table': 'monitor_probetask_submitlog',
                'ordering': ['-creation'],
            },
        ),
    ]
