# Generated by Django 4.2.9 on 2024-07-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_websitedetectionpoint_auth_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetectionpoint',
            name='mntr_label',
            field=models.CharField(blank=True, default='', help_text='用于区分多个探测点的数据', max_length=32, verbose_name='探测点标签'),
        ),
    ]
