# Generated by Django 4.2.9 on 2024-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_websitedetectionpoint_mntr_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='client_ip',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='IP'),
        ),
    ]
