# Generated by Django 4.2.9 on 2024-01-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_objectsservice_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsservice',
            name='monitor_task_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='记录为服务单元创建的站点监控任务的ID', max_length=36, verbose_name='服务单元对应监控任务ID'),
        ),
    ]
