# Generated by Django 4.2.9 on 2024-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_objectsservice_monitor_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsservice',
            name='version',
            field=models.CharField(blank=True, default='', help_text='服务当前的版本', max_length=32, verbose_name='版本号'),
        ),
    ]
