# Generated by Django 4.2.9 on 2024-05-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_objectsservice_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsservice',
            name='version_update_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='版本号更新时间'),
        ),
    ]
