# Generated by Django 4.2.9 on 2024-07-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_objectsservice_version_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectsservice',
            name='loki_tag',
        ),
        migrations.DeleteModel(
            name='StorageQuota',
        ),
    ]
