# Generated by Django 3.2.13 on 2022-09-23 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChange',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_field', models.CharField(choices=[('title', '工单标题'), ('status', '工单状态'), ('severity', '工单严重程度'), ('description', '工单描述'), ('assigned_to', '工单流转处理人')], max_length=32, verbose_name='字段')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
            ],
            options={
                'verbose_name': '工单更改',
                'verbose_name_plural': '工单更改',
                'db_table': 'ticket_change',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='疑问或问题的简述', max_length=250, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', help_text='客户的疑问或问题的描述', verbose_name='问题描述')),
                ('status', models.CharField(choices=[('open', '打开'), ('canceled', '已取消'), ('progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭'), ('reopened', '重新打开')], default='open', max_length=16, verbose_name='状态')),
                ('service_type', models.CharField(choices=[('account', '账户'), ('server', '云服务器'), ('storage', '对象存储'), ('bill', '计量账单'), ('monitor', '监控'), ('hpc', '高性能计算'), ('hsc', '高安全等级云'), ('other', '其他')], default='other', max_length=16, verbose_name='工单相关服务')),
                ('severity', models.CharField(blank=True, choices=[('critical', '严重'), ('high', '高'), ('normal', '一般'), ('low', '低'), ('verylow', '很低')], default='normal', max_length=16, verbose_name='严重程度')),
                ('submit_time', models.DateTimeField(auto_now_add=True, help_text='工单提交的时间', verbose_name='提交时间')),
                ('modified_time', models.DateTimeField(auto_now=True, help_text='工单最近修改的时间', verbose_name='修改时间')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='提交人用户名')),
                ('contact', models.CharField(blank=True, default='', help_text='工单提交人联系方式', max_length=128, verbose_name='联系方式')),
                ('resolution', models.TextField(blank=True, help_text='向客户提供的解决方案。', null=True, verbose_name='解决方案')),
                ('assigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='分配给')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='工单提交人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'ticket_ticket',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, help_text='工单跟进回复提交的时间', verbose_name='提交时间')),
                ('title', models.CharField(default='', help_text='自动填充，比如工单变更的描述', max_length=250, verbose_name='标题')),
                ('comment', models.TextField(default='', verbose_name='评论')),
                ('fu_type', models.CharField(choices=[('reply', '回复'), ('action', '变更动作')], default='reply', max_length=16, verbose_name='跟进类型')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ticket.ticket', verbose_name='工单')),
                ('ticket_change', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ticket.ticketchange', verbose_name='工单更改')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '工单跟进回复',
                'verbose_name_plural': '工单跟进回复',
                'db_table': 'ticket_followup',
                'ordering': ['-submit_time'],
            },
        ),
    ]
