# Generated by Django 3.2.13 on 2022-11-08 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRating',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=5, help_text='1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)], verbose_name='评分')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, verbose_name='评论')),
                ('submit_time', models.DateTimeField(auto_now_add=True, help_text='提交的时间', verbose_name='提交时间')),
                ('modified_time', models.DateTimeField(auto_now=True, help_text='最近修改的时间', verbose_name='修改时间')),
                ('user_id', models.CharField(blank=True, default='', max_length=36, verbose_name='评价提交人id')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='提交人用户名')),
                ('is_sys_submit', models.BooleanField(default=False, verbose_name='系统默认提交')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_rating', to='ticket.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单评价',
                'verbose_name_plural': '工单评价',
                'db_table': 'ticket_rating',
                'ordering': ['-submit_time'],
            },
        ),
    ]
