# Generated by Django 3.2.13 on 2022-06-22 01:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='余额支付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='券支付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='需要支付的金额，扣除优惠或折扣后的金额', max_digits=10, verbose_name='应付金额'),
        ),
    ]
