# Generated by Django 3.2.13 on 2022-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220622_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_service_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='app服务id'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='resource',
            name='delivered_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='资源交付时间'),
        ),
    ]
