# Generated by Django 4.2.5 on 2023-09-18 03:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='mntr_site_base',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='站点监控每天基础监控费用', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='站点监控每天基础费用'),
        ),
        migrations.AddField(
            model_name='price',
            name='mntr_site_security',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='站点监控每天安全监控费用', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='站点监控每天安全监控费用'),
        ),
        migrations.AddField(
            model_name='price',
            name='mntr_site_tamper',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='站点监控每天防篡改监控费用', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='站点监控每天防篡改费用'),
        ),
    ]
