# Generated by Django 4.2.9 on 2024-01-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_price_mntr_site_base_price_mntr_site_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='订购资源数量'),
        ),
    ]
