# Generated by Django 3.2.5 on 2022-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220325_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='交易完成时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
        migrations.AddField(
            model_name='order',
            name='trading_status',
            field=models.CharField(choices=[('opening', '交易中'), ('undelivered', '订单资源交付失败'), ('completed', '交易成功'), ('closed', '交易关闭')], default='opening', max_length=16, verbose_name='交易状态'),
        ),
        migrations.AddField(
            model_name='resource',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='资源交付结果描述'),
        ),
        migrations.AddField(
            model_name='resource',
            name='instance_remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='资源实例备注'),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_deliver_time',
            field=models.DateTimeField(blank=True, default=None, help_text='用于记录上次交付资源的时间，防止并发重复交付', null=True, verbose_name='上次交付创建资源时间'),
        ),
    ]
