# Generated by Django 3.2.13 on 2023-05-09 06:45
import math

from django.db import migrations

from order.managers.instance_configs import ServerConfig
from utils.model import ResourceType


def order_ram_mb_to_gb(apps, schema_editor):
    model_cls = apps.get_model("order", "Order")
    qs = model_cls.objects.filter(resource_type=ResourceType.VM.value).all()
    change_count = 0
    for od in qs:
        try:
            if isinstance(od.instance_config, dict):
                ram_mib = od.instance_config.get(ServerConfig.KEY_RAM, 0)
                if ram_mib > 1000:
                    ram_gib = math.ceil(ram_mib / 1024)
                    od.instance_config[ServerConfig.KEY_RAM] = ram_gib
                    od.save(update_fields=['instance_config'])
                    change_count += 1
        except Exception as exc:
            print(f'Changed order({od.id}) server ram unit from MiB to GiB error: {str(exc)}')
            raise exc

    print(f'Changed order server ram unit from MiB to GiB OK, all {len(qs)}, changed {change_count}')


def order_ram_gb_to_mb(apps, schema_editor):
    model_cls = apps.get_model("order", "Order")
    qs = model_cls.objects.filter(resource_type=ResourceType.VM.value).all()
    change_count = 0
    for od in qs:
        try:
            if isinstance(od.instance_config, dict):
                ram_gib = od.instance_config.get(ServerConfig.KEY_RAM, 0)
                if ram_gib < 1000:
                    od.instance_config[ServerConfig.KEY_RAM] = ram_gib * 1024
                    od.save(update_fields=['instance_config'])
                    change_count += 1
        except Exception as exc:
            print(f'Changed order({od.id}) server ram unit from GiB to MiB error: {str(exc)}')
            raise exc

    print(f'Changed order server ram unit from GiB to MiB OK, all {len(qs)}, changed {change_count}')


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payment_history_id'),
    ]

    operations = [
        migrations.RunPython(code=order_ram_mb_to_gb, reverse_code=order_ram_gb_to_mb)
    ]
