# Generated by Django 4.2.9 on 2024-02-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='instance_delete_time',
            field=models.DateTimeField(blank=True, default=None, help_text='不为空时，表示对应的资源删除的时间', null=True, verbose_name='资源删除时间'),
        ),
    ]
