# Generated by Django 4.2.9 on 2024-03-19 09:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='scan_host',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='安全扫描host主机每次费用', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='主机安全扫描每次费用'),
        ),
        migrations.AddField(
            model_name='price',
            name='scan_web',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='安全扫描WEB每次费用', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='站点安全扫描每次费用'),
        ),
    ]
